;
;	This file is automatically generated
;
;
;	This file is automatically generated.
;
C64_END                  = $80 ; $80 end
C64_FOR                  = $81 ; $81 for
C64_NEXT                 = $82 ; $82 next
C64_DATA                 = $83 ; $83 data
C64_INPUTHASH            = $84 ; $84 input#
C64_INPUT                = $85 ; $85 input
C64_DIM                  = $86 ; $86 dim
C64_READ                 = $87 ; $87 read
C64_LET                  = $88 ; $88 let
C64_GOTO                 = $89 ; $89 goto
C64_RUN                  = $8a ; $8a run
C64_IF                   = $8b ; $8b if
C64_RESTORE              = $8c ; $8c restore
C64_GOSUB                = $8d ; $8d gosub
C64_RETURN               = $8e ; $8e return
C64_REM                  = $8f ; $8f rem
C64_STOP                 = $90 ; $90 stop
C64_ON                   = $91 ; $91 on
C64_WAIT                 = $92 ; $92 wait
C64_LOAD                 = $93 ; $93 load
C64_SAVE                 = $94 ; $94 save
C64_VERIFY               = $95 ; $95 verify
C64_DEF                  = $96 ; $96 def
C64_POKE                 = $97 ; $97 poke
C64_PRINTHASH            = $98 ; $98 print#
C64_PRINT                = $99 ; $99 print
C64_CONT                 = $9a ; $9a cont
C64_LIST                 = $9b ; $9b list
C64_CLR                  = $9c ; $9c clr
C64_CMD                  = $9d ; $9d cmd
C64_SYS                  = $9e ; $9e sys
C64_OPEN                 = $9f ; $9f open
C64_CLOSE                = $a0 ; $a0 close
C64_GET                  = $a1 ; $a1 get
C64_NEW                  = $a2 ; $a2 new
C64_TABLB                = $a3 ; $a3 tab(
C64_TO                   = $a4 ; $a4 to
C64_FN                   = $a5 ; $a5 fn
C64_SPCLB                = $a6 ; $a6 spc(
C64_THEN                 = $a7 ; $a7 then
C64_NOT                  = $a8 ; $a8 not
C64_STEP                 = $a9 ; $a9 step
C64_PLUS                 = $aa ; $aa +
C64_MINUS                = $ab ; $ab -
C64_TIMES                = $ac ; $ac *
C64_DIVIDE               = $ad ; $ad /
C64_POWER                = $ae ; $ae ^
C64_AND                  = $af ; $af and
C64_OR                   = $b0 ; $b0 or
C64_GREATER              = $b1 ; $b1 >
C64_EQUAL                = $b2 ; $b2 =
C64_LESS                 = $b3 ; $b3 <
C64_SGN                  = $b4 ; $b4 sgn
C64_INT                  = $b5 ; $b5 int
C64_ABS                  = $b6 ; $b6 abs
C64_USR                  = $b7 ; $b7 usr
C64_FRE                  = $b8 ; $b8 fre
C64_POS                  = $b9 ; $b9 pos
C64_SQR                  = $ba ; $ba sqr
C64_RND                  = $bb ; $bb rnd
C64_LOG                  = $bc ; $bc log
C64_EXP                  = $bd ; $bd exp
C64_COS                  = $be ; $be cos
C64_SIN                  = $bf ; $bf sin
C64_TAN                  = $c0 ; $c0 tan
C64_ATN                  = $c1 ; $c1 atn
C64_PEEK                 = $c2 ; $c2 peek
C64_LEN                  = $c3 ; $c3 len
C64_STRDOLLAR            = $c4 ; $c4 str$
C64_VAL                  = $c5 ; $c5 val
C64_ASC                  = $c6 ; $c6 asc
C64_CHRDOLLAR            = $c7 ; $c7 chr$
C64_LEFTDOLLAR           = $c8 ; $c8 left$
C64_RIGHTDOLLAR          = $c9 ; $c9 right$
C64_MIDDOLLAR            = $ca ; $ca mid$
C64_GO                   = $cb ; $cb go
C64_PI                   = $ff ; $ff pi
C64_GPCMD_C              = $ce78 ; $ce78 gp.c
C64_GPCMD_Y              = $ce79 ; $ce79 gp.y
C64_GPCMD_X              = $ce7a ; $ce7a gp.x
C64_GPCMD_A              = $ce7b ; $ce7b gp.a
C64_GPCMD_CALL           = $ce7c ; $ce7c gp.call
C64_GPCMD_EXITDO         = $ce7d ; $ce7d gp.exitdo
C64_GPCMD_LOOP           = $ce7e ; $ce7e gp.loop
C64_GPCMD_DO             = $ce7f ; $ce7f gp.do
C64_MON                  = $ce80 ; $ce80 mon
C64_DOS                  = $ce81 ; $ce81 dos
C64_OLD                  = $ce82 ; $ce82 old
C64_GEOS                 = $ce83 ; $ce83 geos
C64_VPOKE                = $ce84 ; $ce84 vpoke
C64_VLOAD                = $ce85 ; $ce85 vload
C64_SCREEN               = $ce86 ; $ce86 screen
C64_PSET                 = $ce87 ; $ce87 pset
C64_LINE                 = $ce88 ; $ce88 line
C64_FRAME                = $ce89 ; $ce89 frame
C64_RECT                 = $ce8a ; $ce8a rect
C64_CHAR                 = $ce8b ; $ce8b char
C64_MOUSE                = $ce8c ; $ce8c mouse
C64_COLOR                = $ce8d ; $ce8d color
C64_TEST                 = $ce8e ; $ce8e test
C64_RESET                = $ce8f ; $ce8f reset
C64_CLS                  = $ce90 ; $ce90 cls
C64_CODEX                = $ce91 ; $ce91 codex
C64_LOCATE               = $ce92 ; $ce92 locate
C64_BOOT                 = $ce93 ; $ce93 boot
C64_KEYMAP               = $ce94 ; $ce94 keymap
C64_BLOAD                = $ce95 ; $ce95 bload
C64_BVLOAD               = $ce96 ; $ce96 bvload
C64_BVERIFY              = $ce97 ; $ce97 bverify
C64_BANK                 = $ce98 ; $ce98 bank
C64_FMINIT               = $ce99 ; $ce99 fminit
C64_FMNOTE               = $ce9a ; $ce9a fmnote
C64_FMDRUM               = $ce9b ; $ce9b fmdrum
C64_FMINST               = $ce9c ; $ce9c fminst
C64_FMVIB                = $ce9d ; $ce9d fmvib
C64_FMFREQ               = $ce9e ; $ce9e fmfreq
C64_FMVOL                = $ce9f ; $ce9f fmvol
C64_FMPAN                = $cea0 ; $cea0 fmpan
C64_FMPLAY               = $cea1 ; $cea1 fmplay
C64_FMCHORD              = $cea2 ; $cea2 fmchord
C64_FMPOKE               = $cea3 ; $cea3 fmpoke
C64_PSGINIT              = $cea4 ; $cea4 psginit
C64_PSGNOTE              = $cea5 ; $cea5 psgnote
C64_PSGVOL               = $cea6 ; $cea6 psgvol
C64_PSGWAV               = $cea7 ; $cea7 psgwav
C64_PSGFREQ              = $cea8 ; $cea8 psgfreq
C64_PSGPAN               = $cea9 ; $cea9 psgpan
C64_PSGPLAY              = $ceaa ; $ceaa psgplay
C64_PSGCHORD             = $ceab ; $ceab psgchord
C64_REBOOT               = $ceac ; $ceac reboot
C64_POWEROFF             = $cead ; $cead poweroff
C64_I2CPOKE              = $ceae ; $ceae i2cpoke
C64_SLEEP                = $ceaf ; $ceaf sleep
C64_BSAVE                = $ceb0 ; $ceb0 bsave
C64_MENU                 = $ceb1 ; $ceb1 menu
C64_REN                  = $ceb2 ; $ceb2 ren
C64_LINPUTHASH           = $ceb3 ; $ceb3 linput#
C64_LINPUT               = $ceb4 ; $ceb4 linput
C64_BINPUTHASH           = $ceb5 ; $ceb5 binput#
C64_HELP                 = $ceb6 ; $ceb6 help
C64_BANNER               = $ceb7 ; $ceb7 banner
C64_EXEC                 = $ceb8 ; $ceb8 exec
C64_TILE                 = $ceb9 ; $ceb9 tile
C64_EDIT                 = $ceba ; $ceba edit
C64_SPRITE               = $cebb ; $cebb sprite
C64_SPRMEM               = $cebc ; $cebc sprmem
C64_MOVSPR               = $cebd ; $cebd movspr
C64_BASLOAD              = $cebe ; $cebe basload
C64_OVAL                 = $cebf ; $cebf oval
C64_RING                 = $cec0 ; $cec0 ring
C64_HBLOAD               = $cec1 ; $cec1 hbload
C64_VPEEK                = $ced0 ; $ced0 vpeek
C64_MX                   = $ced1 ; $ced1 mx
C64_MY                   = $ced2 ; $ced2 my
C64_MB                   = $ced3 ; $ced3 mb
C64_JOY                  = $ced4 ; $ced4 joy
C64_HEXDOLLAR            = $ced5 ; $ced5 hex$
C64_BINDOLLAR            = $ced6 ; $ced6 bin$
C64_I2CPEEK              = $ced7 ; $ced7 i2cpeek
C64_POINTER              = $ced8 ; $ced8 pointer
C64_STRPTR               = $ced9 ; $ced9 strptr
C64_RPTDOLLAR            = $ceda ; $ceda rpt$
C64_MWHEEL               = $cedb ; $cedb mwheel
C64_TDATA                = $cedc ; $cedc tdata
C64_TATTR                = $cedd ; $cedd tattr
C64_MOD                  = $cede ; $cede mod
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		common.inc
;		Purpose:	Common includes/defines/setups
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

; ************************************************************************************************
;
;										Configuration options
;
;			  Addresses should be on page boundaries (except for ZeroPageMandatory)
;
; ************************************************************************************************
;
;		Where to assemble the runnable code. Happy now , Dave ?
;
;		Weak so the standalone resident-runtime build (GPC.RT.nnn.BIN) can override it to RTBASE
;		with -D CodeStart on the command line; every other build keeps $801.
;
		.weak
CodeStart = $801
		.endweak
;
;		Variables that have to be in zero page because it's used in (xx),y
;
ZeroPageMandatory = $22
;
;		Variables that can go anywhere
;
MemoryStorage = $400
;
;		Resident-runtime (GPC.RT.nnn.BIN) ABI -- see application/source/compiler/bootstrap.asm and
;		runtime/source/main/00rt.header. RTBASE is the fixed home the standalone runtime is linked
;		at and loaded to; a shared-mode program's bootstrap checks the magic there, loads it if
;		absent, and enters at RT_ENTRY. RTBASE is PINNED (baked into every shared program's
;		bootstrap), so it is an ABI constant, not auto-computed; zzrt.footer guards it against the
;		runtime outgrowing $9F00.
;
;
;		RTBASE moved $7300 -> $7000 on 31st July 2026 (RT_ABI 1 -> 2). The runtime had outgrown the
;		$9F00 I/O page by 447 bytes and zzrt.footer's guard had been failing the gpc-rt link for
;		some time -- shared mode could not be built at all. Three pages down frees 768 bytes and
;		leaves ~320 spare, at the cost of the same 768 bytes of per-program workspace (~3% of the
;		~26K a shared program gets). If it happens again, lower this and bump RT_ABI together.
;
;
;		AND AGAIN on 16th August 2026, exactly as warned above. The runtime had crept to $9EFF --
;		ONE byte under the ceiling -- so the ~200 bytes added by ReuseForFrame, GP.EXITDO and
;		GP.CALL overflowed it.
;
;		EIGHT pages down this time, not the three that just proved too timid. Every move of RTBASE
;		costs an RT_ABI bump (a resident runtime is keyed on the ordinal, and one built at another
;		base is not interchangeable), so the cheap moment to take the room is while a bump is
;		already happening -- RT_ABI was going 5 -> 6 for GP.CALL's opcodes regardless. Four pages
;		would have left 940 bytes, which does NOT cover the ~1,545 GP.BASIC still has to add;
;		eight leaves ~1,960 and ends the matter. Cost is 2K of the ~26K a shared program gets.
;
RTBASE = $6800 								; resident runtime home ($6800..$9EFF, ~13.7K)
RT_ENTRY = RTBASE+4 						; 4-byte magic at RTBASE, then jmp StartRuntime
PCODE_PAGE = $09 							; shared-mode p-code base page ($0900, page-aligned)
MIN_WS_PAGES = 16 							; smallest workspace a shared program keeps (4K)
;
;		Pages left free between the end of the object code and the start of the workspace, for
;		the runtime (FOR/GOSUB) frame stack. clr.asm puts runtimeStackPtr at storeStartHigh-1:$FF
;		and grows it DOWNWARD, so without a gap here a deep call chain walks back into the code.
;
;		BOTH ends need this number and they must agree, which is why it lives here rather than
;		with either of them. The COMPILER spends it -- object.asm adds it when it works out where
;		a program's workspace starts, in both embedded and shared modes. The RUNTIME polices it --
;		StartRuntime turns storeStartHigh minus this into the floor StackOpenFrame refuses to go
;		below. Change it in one place and a program compiled by the old engine, running under a
;		new runtime, gets a floor that is not where its gap is.
;
FrameStackPages = 16 						; 4K, ~250 frames
;
;		RT_ABI is the runtime's ABI ordinal, and it is the ONE place it is written down. It drives
;		the 4-byte magic at RTBASE ("GPC" + the digit), which the bootstrap compares to answer a
;		single question: is a runtime already resident, and is it one I can safely enter? So bump
;		it whenever the runtime layout or entry contract changes -- and only then. A resident
;		runtime from a DIFFERENT engine build but the same ABI is deliberately still reused.
;
;		The runtime's FILE NAME does not come from here. It carries the engine's BUILD number
;		(source/application/buildnum.txt) -- see scripts/rtname.py, which names the built file,
;		and bootstrap.asm, which formats the same number into the name a compiled program looks
;		for. That is a different question: which runtime file is mine? It pins a program to the
;		exact runtime it was built against, and since the build number bumps on every engine
;		build, shared programs must be recompiled whenever the engine is rebuilt.
;
;		2 -> 3 on 16th August 2026: PCD_ARRAY1 joined the table, and p-code IDs are handed out in
;		the order the ;; [name] markers are scanned, so every opcode after "array1" shifted up by
;		one. A resident runtime of the same ABI is deliberately reused across engine builds --
;		and with renumbered opcodes that would dispatch most of the table to the wrong handler.
;		This is the guard that stops it.
;
;		3 -> 4 on 16th August 2026: GP.DO / GP.LOOP joined the table. Same mechanism as the 2 -> 3
;		bump above -- "do.asm" sorts ahead of "for.asm" in the commands directory, so the two new
;		markers landed at $96/$97 and shifted every opcode from "for" upward by two.
;
;		4 -> 5 on 16th August 2026: GP.EXITDO joined the table as the system token ".exitdo". This
;		one is NOT a renumbering -- it was appended after ".deferror" precisely so that every
;		existing opcode keeps its ID. The bump is still required in the other direction: an object
;		using $DF would dispatch off the end of an ABI 4 runtime's vector table.
;
;		5 -> 6 on 16th August 2026: GP.CALL and the GP.A/GP.X/GP.Y/GP.C value words. This one IS a
;		renumbering -- "gpcall.asm" sorts mid-list in the commands directory, so the four unshifted
;		markers shifted every opcode above them, and the shifted gp.call did the same to the
;		shifted range.
;
RT_ABI = 6 									; runtime ABI ordinal -> "GPC6" magic (NOT the file name)

; ************************************************************************************************
;
;									Set up code and data sections
;
; ************************************************************************************************

		* = ZeroPageMandatory 				; *must* be in zero page
		.dsection zeropage

		* = MemoryStorage 					; doesn't matter if zero page or not
		.dsection storage
StorageEnd:

		* = CodeStart
		.dsection code

;
;		storage is a 1K hole -- $0400 to $0801, and no further, because the code starts there.
;		Nothing warns you when it runs out: the section simply carries on over the top of the
;		BASIC stub, and the program corrupts itself the first time it writes to the buffer that
;		spilled. It HAD run out, silently, and only survived because the one buffer hanging over
;		the edge was never filled past its fifteenth byte. So say so, loudly.
;
		.cerror StorageEnd > CodeStart, "storage has overflowed into the code - put compiler-only buffers in the code section (see application/source/file-io/read.asm)"

; ************************************************************************************************
;
;										Zero Page Common Usage
;
; ************************************************************************************************

		.section zeropage

codePtr:	 								; address of current line.
		.fill 	2

objPtr: 									; address in code. 
		.fill 	2 							

zTemp0: 									; temporary words used in the interpreter.
		.fill 	2
zTemp1:
		.fill 	2
zTemp2:
		.fill 	2

		.endsection

; ************************************************************************************************
;
;							Insert an Emulator Breakpoint
;
; ************************************************************************************************

debug 		.macro
		.byte 	$DB 						; causes a break in the emulator
		.endm

; ************************************************************************************************
;
;								Set a 2 byte value in memory
;
; ************************************************************************************************

set16 		.macro
		lda 	#((\2) & $FF)
		sta 	0+\1
		lda 	#((\2) >> 8) & $FF
		sta 	1+\1
		.endm

; ************************************************************************************************
;
;										Exit emulation
;
; ************************************************************************************************

exitemu .macro
		stx 	zTemp0
		jmp 	$FFFF
		.endm

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
;
;	This file is automatically generated.
;
error_range .macro
	jmp	ErrorV_range
	.endm
error_value .macro
	jmp	ErrorV_value
	.endm
error_syntax .macro
	jmp	ErrorV_syntax
	.endm
error_type .macro
	jmp	ErrorV_type
	.endm
error_unimplemented .macro
	jmp	ErrorV_unimplemented
	.endm
error_assert .macro
	jmp	ErrorV_assert
	.endm
error_line .macro
	jmp	ErrorV_line
	.endm
error_internal .macro
	jmp	ErrorV_internal
	.endm
error_divzero .macro
	jmp	ErrorV_divzero
	.endm
error_structure .macro
	jmp	ErrorV_structure
	.endm
error_stop .macro
	jmp	ErrorV_stop
	.endm
error_data .macro
	jmp	ErrorV_data
	.endm
error_undeclared .macro
	jmp	ErrorV_undeclared
	.endm
error_redefine .macro
	jmp	ErrorV_redefine
	.endm
error_index .macro
	jmp	ErrorV_index
	.endm
error_memory .macro
	jmp	ErrorV_memory
	.endm
error_channel .macro
	jmp	ErrorV_channel
	.endm
error_break .macro
	jmp	ErrorV_break
	.endm
error_toobig .macro
	jmp	ErrorV_toobig
	.endm
;
;	This file is automatically generated
;
PCD_STARTBINARY = $80
PCD_ENDBINARY = $8d
PCD_STARTCOMMAND = $8d
PCD_ENDCOMMAND = $d5
PCD_STARTSYSTEM = $d5
PCD_ENDSYSTEM = $e4

PCD_PLUS             = $80 ; +
PCD_MINUS            = $81 ; -
PCD_TIMES            = $82 ; *
PCD_DIVIDE           = $83 ; /
PCD_POWER            = $84 ; ^
PCD_AND              = $85 ; and
PCD_OR               = $86 ; or
PCD_GREATER          = $87 ; >
PCD_EQUAL            = $88 ; =
PCD_LESS             = $89 ; <
PCD_GREATEREQUAL     = $8a ; >=
PCD_LESSGREATER      = $8b ; <>
PCD_LESSEQUAL        = $8c ; <=
PCD_ABS              = $8d ; abs
PCD_ARRAY1           = $8e ; array1
PCD_ARRAY            = $8f ; array
PCD_ASC              = $90 ; asc
PCD_ASSERT           = $91 ; assert
PCD_BINDOLLAR        = $92 ; bin$
PCD_PRINTCMD_CHR     = $93 ; print.chr
PCD_CHRDOLLAR        = $94 ; chr$
PCD_SCMD_CMP         = $95 ; s.cmp
PCD_GPCMD_DO         = $96 ; gp.do
PCD_GPCMD_LOOP       = $97 ; gp.loop
PCD_FOR              = $98 ; for
PCD_FRE              = $99 ; fre
PCD_GET              = $9a ; get
PCD_RETURN           = $9b ; return
PCD_GPCMD_A          = $9c ; gp.a
PCD_GPCMD_X          = $9d ; gp.x
PCD_GPCMD_Y          = $9e ; gp.y
PCD_GPCMD_C          = $9f ; gp.c
PCD_PSET             = $a0 ; pset
PCD_LINE             = $a1 ; line
PCD_RECT             = $a2 ; rect
PCD_FRAME            = $a3 ; frame
PCD_OVAL             = $a4 ; oval
PCD_RING             = $a5 ; ring
PCD_CHAR             = $a6 ; char
PCD_HEXDOLLAR        = $a7 ; hex$
PCD_INPUT            = $a8 ; input
PCD_INPUTDOLLAR      = $a9 ; input$
PCD_INPUTCMD_START   = $aa ; input.start
PCD_LEN              = $ab ; len
PCD_FCMD_CMP         = $ac ; f.cmp
PCD_INTCMD_DIV       = $ad ; int.div
PCD_MOD              = $ae ; mod
PCD_NEGATE           = $af ; negate
PCD_NEWCMD_LINE      = $b0 ; new.line
PCD_NEXT             = $b1 ; next
PCD_NOT              = $b2 ; not
PCD_ON               = $b3 ; on
PCD_MOREON           = $b4 ; moreon
PCD_PEEK             = $b5 ; peek
PCD_PI               = $b6 ; pi
PCD_POKE             = $b7 ; poke
PCD_POS              = $b8 ; pos
PCD_GETCHANNEL       = $b9 ; getchannel
PCD_SETCHANNEL       = $ba ; setchannel
PCD_PRINTCMD_N       = $bb ; print.n
PCD_PRINTCMD_S       = $bc ; print.s
PCD_READ             = $bd ; read
PCD_READDOLLAR       = $be ; read$
PCD_RND              = $bf ; rnd
PCD_CONCAT           = $c0 ; concat
PCD_SGN              = $c1 ; sgn
PCD_PRINTCMD_TAB     = $c2 ; print.tab
PCD_PRINTCMD_POS     = $c3 ; print.pos
PCD_PRINTCMD_SPC     = $c4 ; print.spc
PCD_STRDOLLAR        = $c5 ; str$
PCD_LEFTDOLLAR       = $c6 ; left$
PCD_RIGHTDOLLAR      = $c7 ; right$
PCD_MIDDOLLAR        = $c8 ; mid$
PCD_SWAP             = $c9 ; swap
PCD_TI               = $ca ; ti
PCD_TIDOLLAR         = $cb ; ti$
PCD_USR              = $cc ; usr
PCD_VAL              = $cd ; val
PCD_CLOSE            = $ce ; close
PCD_EXIT             = $cf ; exit
PCD_DEBUG            = $d0 ; debug
PCD_OPEN             = $d1 ; open
PCD_SCREEN           = $d2 ; screen
PCD_VPOKE            = $d3 ; vpoke
PCD_VPEEK            = $d4 ; vpeek
PCD_CMD_SHIFT        = $d5 ; .shift
PCD_CMD_BYTE         = $d6 ; .byte
PCD_CMD_WORD         = $d7 ; .word
PCD_CMD_FLOAT        = $d8 ; .float
PCD_CMD_STRING       = $d9 ; .string
PCD_CMD_DATA         = $da ; .data
PCD_CMD_GOTO         = $db ; .goto
PCD_CMD_GOSUB        = $dc ; .gosub
PCD_CMD_GOTOCMD_Z    = $dd ; .goto.z
PCD_CMD_GOTOCMD_NZ   = $de ; .goto.nz
PCD_CMD_VARSPACE     = $df ; .varspace
PCD_CMD_RESTORE      = $e0 ; .restore
PCD_CMD_FNGOSUB      = $e1 ; .fngosub
PCD_CMD_DEFERROR     = $e2 ; .deferror
PCD_CMD_EXITDO       = $e3 ; .exitdo
PCD_CLR              = $d580 ; clr
PCD_DIM              = $d581 ; dim
PCD_END              = $d582 ; end
PCD_GPCMD_CALL       = $d583 ; gp.call
PCD_JOY              = $d584 ; joy
PCD_INT              = $d585 ; int
PCD_SQR              = $d586 ; sqr
PCD_LOG              = $d587 ; log
PCD_EXP              = $d588 ; exp
PCD_COS              = $d589 ; cos
PCD_SIN              = $d58a ; sin
PCD_TAN              = $d58b ; tan
PCD_ATN              = $d58c ; atn
PCD_LINPUT           = $d58d ; linput
PCD_BINPUT           = $d58e ; binput
PCD_LOAD             = $d58f ; load
PCD_BLOAD            = $d590 ; bload
PCD_BVLOAD           = $d591 ; bvload
PCD_VLOAD            = $d592 ; vload
PCD_BSAVE            = $d593 ; bsave
PCD_BVERIFY          = $d594 ; bverify
PCD_POWEROFF         = $d595 ; poweroff
PCD_RESET            = $d596 ; reset
PCD_REBOOT           = $d597 ; reboot
PCD_MOUSE            = $d598 ; mouse
PCD_MB               = $d599 ; mb
PCD_MX               = $d59a ; mx
PCD_MY               = $d59b ; my
PCD_MWHEEL           = $d59c ; mwheel
PCD_RPTDOLLAR        = $d59d ; rpt$
PCD_SPRITE           = $d59e ; sprite
PCD_SPRMEM           = $d59f ; sprmem
PCD_MOVSPR           = $d5a0 ; movspr
PCD_ST               = $d5a1 ; st
PCD_STOP             = $d5a2 ; stop
PCD_SYS              = $d5a3 ; sys
PCD_TDATA            = $d5a4 ; tdata
PCD_TATTR            = $d5a5 ; tattr
PCD_TILE             = $d5a6 ; tile
PCD_TICMD_WRITE      = $d5a7 ; ti.write
PCD_TIDOLLARCMD_WRITE = $d5a8 ; ti$.write
PCD_WAIT             = $d5a9 ; wait
PCD_I2CPOKE          = $d5aa ; i2cpoke
PCD_I2CPEEK          = $d5ab ; i2cpeek
PCD_BANK             = $d5ac ; bank
PCD_SLEEP            = $d5ad ; sleep
PCD_FMINIT           = $d5ae ; fminit
PCD_FMNOTE           = $d5af ; fmnote
PCD_FMDRUM           = $d5b0 ; fmdrum
PCD_FMINST           = $d5b1 ; fminst
PCD_FMVIB            = $d5b2 ; fmvib
PCD_FMFREQ           = $d5b3 ; fmfreq
PCD_FMVOL            = $d5b4 ; fmvol
PCD_FMPAN            = $d5b5 ; fmpan
PCD_FMPLAY           = $d5b6 ; fmplay
PCD_FMCHORD          = $d5b7 ; fmchord
PCD_FMPOKE           = $d5b8 ; fmpoke
PCD_PSGINIT          = $d5b9 ; psginit
PCD_PSGNOTE          = $d5ba ; psgnote
PCD_PSGVOL           = $d5bb ; psgvol
PCD_PSGWAV           = $d5bc ; psgwav
PCD_PSGFREQ          = $d5bd ; psgfreq
PCD_PSGPAN           = $d5be ; psgpan
PCD_PSGPLAY          = $d5bf ; psgplay
PCD_PSGCHORD         = $d5c0 ; psgchord
PCD_CLS              = $d5c1 ; cls
PCD_LOCATE           = $d5c2 ; locate
PCD_COLOR            = $d5c3 ; color
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		errdispatch.asm
;		Purpose:	Dispatch error handler
;		Created:	8th October 2023
;		Reviewed: 	No
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section code

; ************************************************************************************************
;
;								Set error handler to YX
;
; ************************************************************************************************

SetErrorHandler:
		sty 	ErrorHandlerVector+1
		stx 	ErrorHandlerVector
		rts
		
; ************************************************************************************************
;
;								Go to current error handler
;
; ************************************************************************************************

CallErrorHandler:
		jmp 	(ErrorHandlerVector)

		.send code

		.section storage
ErrorHandlerVector:
		.fill 	2
		.send storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
;
;	This file is automatically generated.
;
	.section code
ErrorV_range:
	jsr	CallErrorHandler
	.text	"OUT OF RANGE",0
ErrorV_value:
	jsr	CallErrorHandler
	.text	"BAD VALUE",0
ErrorV_syntax:
	jsr	CallErrorHandler
	.text	"SYNTAX ERROR",0
ErrorV_type:
	jsr	CallErrorHandler
	.text	"TYPE MISMATCH",0
ErrorV_unimplemented:
	jsr	CallErrorHandler
	.text	"NOT IMPLEMENTED",0
ErrorV_assert:
	jsr	CallErrorHandler
	.text	"ASSERT FAIL",0
ErrorV_line:
	jsr	CallErrorHandler
	.text	"UNKNOWN LINE NUMBER",0
ErrorV_internal:
	jsr	CallErrorHandler
	.text	"INTERNAL ERROR",0
ErrorV_divzero:
	jsr	CallErrorHandler
	.text	"DIVIDE BY ZERO",0
ErrorV_structure:
	jsr	CallErrorHandler
	.text	"STRUCTURE IMBALANCE",0
ErrorV_stop:
	jsr	CallErrorHandler
	.text	"PROGRAM STOPPED",0
ErrorV_data:
	jsr	CallErrorHandler
	.text	"OUT OF DATA",0
ErrorV_undeclared:
	jsr	CallErrorHandler
	.text	"UNKNOWN ARRAY",0
ErrorV_redefine:
	jsr	CallErrorHandler
	.text	"ARRAY REDEFINED",0
ErrorV_index:
	jsr	CallErrorHandler
	.text	"BAD ARRAY INDEX",0
ErrorV_memory:
	jsr	CallErrorHandler
	.text	"OUT OF MEMORY",0
ErrorV_channel:
	jsr	CallErrorHandler
	.text	"INPUT/OUTPUT ERROR",0
ErrorV_break:
	jsr	CallErrorHandler
	.text	"BREAK PRESSED",0
ErrorV_toobig:
	jsr	CallErrorHandler
	.text	"PROGRAM TOO BIG",0
	.send code
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		forward.asm
;		Purpose:	Move object pointer forward
;		Created:	18th April 2023
;		Reviewed: 	No
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section code

; ************************************************************************************************
;
;								Move objPtr forwards. CS if end
;
; ************************************************************************************************

MoveObjectForward:

		lda 	(objPtr) 					; get next
		
		cmp 	#$FF  						
		beq 	_MOFEnd

		cmp 	#$40 						; 00-3F
		bcc 	_MOFAdvance1 				; forward 1

		ldy 	#2 							; 40-6F
		cmp 	#$70 						; forward 2
		bcc 	_MOFAdvanceY 				

		cmp 	#PCD_STARTSYSTEM 			; 70 - System tokens.
		bcc 	_MOFAdvance1 				; forward 1

		tay 								; read the size.
		lda 	MOFSizeTable-PCD_STARTSYSTEM,y
		tay
		iny 								; add 1 for the system token.
		bne 	_MOFAdvanceY 				; if 0, was $FF thus a string/data skip.

		ldy 	#1 							; get length byte
		lda 	(objPtr),y
		tay 								; into Y.

		clc
		lda 	objPtr						; add 2 to the object pointer
		adc 	#2
		sta 	objPtr
		bcc 	_MOFNoCarry1
		inc 	objPtr+1
_MOFNoCarry1:		
		bra 	_MOFAdvanceY

_MOFAdvance1:
		ldy 	#1
_MOFAdvanceY:				
		tya 								; add Y to objPtr
		clc
		adc 	objPtr
		sta 	objPtr
		bcc 	_MOFNoCarry2
		inc 	objPtr+1
_MOFNoCarry2:		
		clc 								; not completed.
		rts
		;
		;		At the end so advance past $FF end marker and return CS.
		;
_MOFEnd:
		inc 	objPtr
		bne 	_MOFENoCarry
		inc 	objPtr+1
_MOFENoCarry:
		sec
		rts		

		.send code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
;
;	This file is automatically generated
;
.section code
MOFSizeTable:
	.byte	1         	; $d5 .shift
	.byte	1         	; $d6 .byte
	.byte	2         	; $d7 .word
	.byte	6         	; $d8 .float
	.byte	255       	; $d9 .string
	.byte	255       	; $da .data
	.byte	2         	; $db .goto
	.byte	2         	; $dc .gosub
	.byte	2         	; $dd .goto.z
	.byte	2         	; $de .goto.nz
	.byte	2         	; $df .varspace
	.byte	2         	; $e0 .restore
	.byte	2         	; $e1 .fngosub
	.byte	0         	; $e2 .deferror
	.byte	2         	; $e3 .exitdo
.send code
