# *******************************************************************************************
# *******************************************************************************************
#
#       Name :      build.py
#       Purpose :   Create build file
#       Date :      11th April 2023
#       Author :    Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,re,sys

# *******************************************************************************************
#
#										Builder class
#
# *******************************************************************************************

class Builder(object):
	def __init__(self,searchDir = "."):
		self.incFiles = []
		self.asmFiles = []
		self.defFiles = []
		self.scanForFiles(searchDir)
	#
	#		Scan source the for required modules.
	#
	def scanForFiles(self,searchDir):
		for root,dirs,files in os.walk(searchDir+os.sep+"source"):
			for f in files:
				if not f.startswith("_"):
					if f.endswith(".inc"):
						self.incFiles.append(root+os.sep+f)
					if f.endswith(".def"):
						self.defFiles.append(root+os.sep+f)
					if f.endswith(".asm"):
						self.asmFiles.append(root+os.sep+f)			

		#
		#		Sort by leafname, then by full path as a tie-breaker. Without the
		#		tie-breaker, files sharing a leafname (e.g. commands/get.asm and
		#		helpers/get.asm) are left in os.walk() order, which varies by platform
		#		and filesystem -- so the same sources linked in a different order and
		#		the build was not reproducible.
		#
		self.asmFiles.sort(key = self.sortKey)
		self.incFiles.sort(key = self.sortKey)
		self.defFiles.sort(key = self.sortKey)

	def sortKey(self,path):
		parts = path.replace("\\",os.sep).replace("/",os.sep).split(os.sep)
		return (parts[-1],parts)

	def createFile(self):
		h = open("_library.asm","w")
		h.write(";\n;\tThis file is automatically generated\n;\n")
		for f in self.incFiles+self.asmFiles:
			for s in open(f).readlines():
				if s.strip().startswith("#include"):
					incFile = os.sep.join(f.split(os.sep)[:-1])+os.sep+(s.replace('"',"").strip()[8:].strip())
					for s2 in open(incFile).readlines():
						h.write(s2)
				else:
					h.write(s)				
		h.close()

	def getINCFiles(self):
		return self.incFiles
	def getASMFiles(self):
		return self.asmFiles
	def getDEFFiles(self):
		return self.defFiles

# *******************************************************************************************
#
#		Every .asm the RUNTIME contributes, across BOTH trees, in one canonical order.
#
#		The runtime is now assembled from two source trees. runtime/ is the interpreter; the GP
#		handlers live apart in gp-runtime/ so they can be linked LAST and sit at the tail of the
#		image, where a future pass can truncate them out of an object that references none of
#		them (docs/blitz/GP-BASIC.TIERS.md, tier 7). Handlers are reachable only through their
#		VectorTable slot, so nothing below them ever calls in.
#
#		THIS EXISTS SO THE TWO SCANNERS CANNOT DISAGREE. pcode.py assigns a command's opcode by
#		its POSITION in this list and vectors.py fills the slot at that position from the marker
#		it finds -- so a file visible to one and not the other silently points an opcode at
#		"Unimplemented", which is a running program doing the wrong thing, not a build failure.
#
#		The combined list is re-sorted with the SAME key, so the split changed no opcode at all:
#		the key is leafname-first, gpcall.asm still sorts between gosub.asm and gpsort.asm no
#		matter which tree holds it. That is deliberate -- moving the files was meant to change
#		the layout and nothing else, and it is checkable (diff the generated pcodetokens.inc).
#		Keep leafnames unique across both trees and it stays true.
#
# *******************************************************************************************

def getRuntimeASMFiles(sourceDir = ".."):
	trees = [Builder(sourceDir+os.sep+"runtime"),Builder(sourceDir+os.sep+"gp-runtime")]
	files = []
	for t in trees:
		files += t.getASMFiles()
	files.sort(key = trees[0].sortKey)
	return files


if __name__ == "__main__":
 	Builder().createFile()
