;
;	This file is automatically generated
;
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		constant.inc
;		Purpose:	Push constant macro
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

; ************************************************************************************************
;
;											load a constant
;
; ************************************************************************************************

pushfloat .macro
		lda 	#\1-Const_Base
		jsr 	LoadConstant
		inx
		.endm

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		atn.asm
;		Purpose:	ATN function.
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculate ATN(x)
;
; ************************************************************************************************

FloatArcTan:
		jsr 	FloatNormalise 					; normalise x

		lda 	NSStatus,x 						; save sign, make absolute
		pha
		stz 	NSStatus,x

		lda 	NSExponent,x 					; $80000000 ^ $E1 is 1.0, so an exponent of -31
		cmp 	#$E1 							; or more means |x| >= 1 and needs the reciprocal.
		bcc 	_UANoFixup 						; ($E2 while the mantissa normalised to bit 30.)

		txa 									; value in +1
		tay
		iny
		jsr 	CopyFloatXY
		lda 	#1 								; 1.0 in +0
		jsr 	FloatSetByte
		inx
		jsr 	FloatDivide
		bcs 	_FATError

		jsr 	CoreAtn 						; calculate the root
		jsr 	CompletePolynomial
		jsr 	FloatNegate 					; make -ve

		.pushfloat Const_PiDiv2 				; add Pi/2
		jsr 	FloatAdd
		bra 	_UAComplete

_UANoFixup:		
		jsr 	CoreAtn
		jsr 	CompletePolynomial
_UAComplete:

		pla 									; apply the result.
		eor 	NSStatus,x
		sta 	NSStatus,x
		clc
		rts

_FATError:
		pla
		sec
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		atn_core.asm
;		Purpose:	Core ATN() polynomial
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculates ATN()
;
; ************************************************************************************************

CoreAtn: 	
		lda 	#AtnCoefficients & $FF
		ldy 	#AtnCoefficients >> 8
		jmp 	CorePolySquared

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
;
;	Automatically generated.
;
	.section code

ExpCoefficients:
	.byte	7
	.dword	$b4583e56 ; 2.1498763701e-05
	.byte	$d1
	.byte	$00
	.dword	$967eb31b ; 0.00014352314037
	.byte	$d4
	.byte	$00
	.dword	$afeee385 ; 0.0013422634825
	.byte	$d7
	.byte	$00
	.dword	$9d841c2a ; 0.0096140170135
	.byte	$da
	.byte	$00
	.dword	$e359580a ; 0.05550512686
	.byte	$dc
	.byte	$00
	.dword	$f5fde7c6 ; 0.2402263846
	.byte	$de
	.byte	$00
	.dword	$b1721810 ; 0.69314718618
	.byte	$e0
	.byte	$00
	.dword	$80000000 ; 1.0
	.byte	$e1
	.byte	$00

SinCoefficients:
	.byte	6
	.dword	$e61a2d1b ; -14.381390672
	.byte	$e4
	.byte	$80
	.dword	$a807fbf8 ; 42.007797122
	.byte	$e6
	.byte	$00
	.dword	$99688901 ; -76.704170257
	.byte	$e7
	.byte	$80
	.dword	$a335dfe1 ; 81.605223686
	.byte	$e7
	.byte	$00
	.dword	$a55de728 ; -41.341702104
	.byte	$e6
	.byte	$80
	.dword	$c90fdaa2 ; 6.2831853069
	.byte	$e3
	.byte	$00
	.dword	$00000000 ; 0.0
	.byte	$00
	.byte	$00

LogCoefficients:
	.byte	4
	.dword	$de56cb79 ; 0.43425594189
	.byte	$df
	.byte	$00
	.dword	$939b0b64 ; 0.57658454124
	.byte	$e0
	.byte	$00
	.dword	$f6389316 ; 0.96180075919
	.byte	$e0
	.byte	$00
	.dword	$b8aa3b20 ; 2.8853900731
	.byte	$e2
	.byte	$00
	.dword	$80000000 ; -0.5
	.byte	$e0
	.byte	$80

AtnCoefficients:
	.byte	12
	.dword	$b383bdd3 ; -0.00068479391189
	.byte	$d6
	.byte	$80
	.dword	$9ef4a6f5 ; 0.0048509421558
	.byte	$d9
	.byte	$00
	.dword	$83fcb010 ; -0.016111701843
	.byte	$db
	.byte	$80
	.dword	$8c1f67ca ; 0.034209638048
	.byte	$dc
	.byte	$00
	.dword	$de53cbc1 ; -0.054279132761
	.byte	$dc
	.byte	$80
	.dword	$9464704c ; 0.07245719654
	.byte	$dd
	.byte	$00
	.dword	$b7ea517a ; -0.089802395378
	.byte	$dd
	.byte	$80
	.dword	$e330887e ; 0.11093241343
	.byte	$dd
	.byte	$00
	.dword	$9244993a ; -0.14283980767
	.byte	$de
	.byte	$80
	.dword	$cccc91c7 ; 0.19999912049
	.byte	$de
	.byte	$00
	.dword	$aaaaaa13 ; -0.33333331568
	.byte	$df
	.byte	$80
	.dword	$80000000 ; 1.0
	.byte	$e1
	.byte	$00
	.dword	$00000000 ; 0.0
	.byte	$00
	.byte	$00
	.send code
;
;	This file is automatically generated.
;
.section code
Const_Base:
Const_1Div2Pi:
	.dword	$a2f9836e ; 0.15915494
	.byte	$de
	.byte	$00
Const_PiDiv2:
	.dword	$c90fdaa2 ; 1.57079633
	.byte	$e1
	.byte	$00
Const_Log2_e:
	.dword	$b8aa3b29 ; 1.44269504
	.byte	$e1
	.byte	$00
Const_sqrt_2:
	.dword	$b504f334 ; 1.41421356
	.byte	$e1
	.byte	$00
Const_sqrt_half:
	.dword	$b504f334 ; 0.70710678
	.byte	$e0
	.byte	$00
Const_pi:
	.dword	$c90fdaa2 ; 3.14159265
	.byte	$e2
	.byte	$00
Const_half:
	.dword	$80000000 ; 0.50000000
	.byte	$e0
	.byte	$00
Const_ln_e:
	.dword	$b17217f8 ; 0.69314718
	.byte	$e0
	.byte	$00
.send code
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		cos.asm
;		Purpose:	Cosine function.
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculate COS(x)
;
; ************************************************************************************************

FloatCosine: 	
		.pushfloat Const_PiDiv2 			; add PI/2
		jsr 	FloatAdd
		jmp 	FloatSine

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		exp.asm
;		Purpose:	Exponent function.
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculate EXP(x)
;
; ************************************************************************************************

FloatExponent:
	
		.pushfloat Const_Log2_e			; multiply by log2 e
		jsr 	FloatMultiply 

		jsr 	_UECopy01 				; copy 0 to 1, get integer part to 1
		inx
		jsr 	FloatIntegerPart
		dex

;
;		The integer part becomes the binary exponent of the result -- it is added straight
;		to NSExponent at the end -- so it has to fit a SIGNED byte. Too large is not an
;		error by itself; the SIGN of the argument decides which. A large POSITIVE argument
;		really does exceed the format, and that is a range error. A large NEGATIVE one only
;		underflows, and 0.0 is the correct answer for exp(-big), not a failure.
;
;		This used to cap the magnitude at 64 in both directions, which was far tighter than
;		the format (value = 32-bit mantissa * 2^signed-exponent, so ~2^127). It cost two
;		real cases: 2^64 -- whose exp() integer part is exactly 64, so it failed by one --
;		and EXP(-45), about 2.9e-20 and comfortably representable.
;
		lda 	NSMantissa1+1,x 		; |int| >= 256, so it cannot be added at all
		ora 	NSMantissa2+1,x
		ora 	NSMantissa3+1,x
		bne 	_UETooBig

		lda 	NSMantissa0+1,x 		; push integer part on stack.
		cmp 	#128 					; must still fit a SIGNED byte to be added below
		bcs 	_UETooBig
		pha

		lda 	NSStatus,x 				; push sign
		pha

		jsr 	FloatFractionalPart		; copy 0 to 1, get fractional part to 0

		pla 
		bpl 	_UEPositive

		inx 							; 1-x
		lda 	#1
		jsr 	FloatSetByte		
		dex
		jsr 	FloatNegate
		inx
		jsr 	FloatAdd

		pla 							; integer part +1 and negated.
		inc 	a
		eor 	#$FF
		inc 	a
		pha

_UEPositive:		
		jsr 	CoreExponent
		jsr 	CompletePolynomial

		pla 							; the integer part, already negated if the argument
		tay 							; was negative. Keep a copy: its sign is what tells
		clc 							; an overflow off the top from one off the bottom.
		adc 	NSExponent,x
		bvs 	_UEExpOutOfRange 		; ADC sets V on signed overflow of the exponent byte
		sta 	NSExponent,x
		clc
		rts

;
;		The exponent does not fit a signed byte. Adding a positive integer part means we
;		went off the top, which is a genuine range error; a negative one means off the
;		bottom, which underflows to zero.
;
_UEExpOutOfRange:
		tya
		bmi 	_UEUnderflow
		bra 	_UERangeError

;
;		|int| was too large to add at all. Same rule, decided by the sign of the argument.
;		That is still slot X, because slot X+1 is where the integer part was taken from.
;
_UETooBig:
		lda 	NSStatus,x
		bpl 	_UERangeError

_UEUnderflow: 							; exp(-big) is 0.0, and that is a success, not an error
		jsr 	FloatSetZero
		clc
		rts

_UECopy01:
		txa
		tay
		iny
		jmp 	CopyFloatXY

_UERangeError:
		sec
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		exp_core.asm
;		Purpose:	Core EXP() polynomial
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculates 2^x
;
; ************************************************************************************************

CoreExponent: 	
		lda 	#ExpCoefficients & $FF
		ldy 	#ExpCoefficients >> 8
		jsr 	CalculateHornerPolynomial
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		horner.asm
;		Purpose:	Calculate Horner Polynomial, table at YA
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									Calculates Horner Polynomial
;
; ************************************************************************************************

CalculateHornerPolynomial:
		sta 	zTemp0 						; save poly data from YA
		sty 	zTemp0+1
		stz 	coefficientCount 			; zero the count.
		stx 	xValueSlot 					; save xValue slot.

		inx 								; set the count to zero.
		jsr 	FloatSetZero
		;
		;		Horner evaluation loop (see coremaths.py)
		;
_CHPLoop:	
		txa 								; copy X-1 to X+1
		tay
		dex
		iny
		jsr 	CopyFloatXY 				; e.g. stack is <current> <x>
		inx
		inx
		jsr 	FloatMultiply 				; times current by X
		inx
		jsr 	GetCoefficient 				; coefficient into X+1
		jsr 	FloatAdd 					; and add
		;
		inc 	coefficientCount
		lda 	coefficientCount
		cmp 	(zTemp0)
		bne 	_CHPLoop
		rts

; ************************************************************************************************
;
;									 Completion
;
; ************************************************************************************************

CompletePolynomial:
		jsr 	FloatMultiply
		inx 								; get the last value
		jsr 	GetCoefficient 			
		jsr 	FloatAdd 					; and add it
		rts

; ************************************************************************************************
;
;								Copy entry X to entry Y
;
; ************************************************************************************************

CopyFloatXY:
		lda 	NSExponent,x
		sta 	NSExponent,y
		lda 	NSStatus,x
		sta 	NSStatus,y

		lda 	NSMantissa0,x
		sta 	NSMantissa0,y
		lda 	NSMantissa1,x
		sta 	NSMantissa1,y
		lda 	NSMantissa2,x
		sta 	NSMantissa2,y
		lda 	NSMantissa3,x
		sta 	NSMantissa3,y
		rts

; ************************************************************************************************
;
;						Get current coefficient to stack,X
;
;		Six bytes per coefficient: four mantissa, exponent, sign (see coremaths.py). As in
;		LoadConstant, the sign no longer rides in bit 7 of the top mantissa byte -- that bit is
;		part of the value now, and masking it off wrecked every coefficient it was set in.
;
; ************************************************************************************************

GetCoefficient:
		phy
		lda 	coefficientCount 			; six bytes per coefficient
		asl 	a 							; x2
		clc
		adc 	coefficientCount 			; x3
		asl 	a 							; x6
		inc 	a 							; +1 for the leading count byte
		tay

		lda 	(zTemp0),y 					; copy mantissa
		sta 	NSMantissa0,x
		iny
		lda 	(zTemp0),y
		sta 	NSMantissa1,x
		iny
		lda 	(zTemp0),y
		sta 	NSMantissa2,x
		iny
		lda 	(zTemp0),y 					; all four mantissa bytes are value
		sta 	NSMantissa3,x
		iny
		lda 	(zTemp0),y
		sta 	NSExponent,x
		iny
		lda 	(zTemp0),y 					; and the sign, on its own
		sta 	NSStatus,x
		ply
		rts

		.send 	code

		.section storage
coefficientCount:
		.fill 	1
xValueSlot:
		.fill 	1
		.send storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		load.asm
;		Purpose:	Load constant offset Y into X+1, preserving X
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									Load Constant
;
;		Six bytes per entry: four mantissa, exponent, sign (see mathconstants.py).
;
;		The sign used to ride in bit 7 of the top mantissa byte and be masked off here. That was
;		safe only while the mantissa normalised to bit 30 and left bit 31 spare; it holds a full
;		32 bits now, so the mask DESTROYED the top bit of every constant and read it back as a
;		minus. Const_Log2_e (1.44269504) came through as -0.442695, which is what made EXP(1)
;		return 2/e and took LOG, SQR and the trig functions with it.
;
; ************************************************************************************************

LoadConstant:
		phy
		tay
		lda 	Const_Base+0,y
		sta 	NSMantissa0+1,x
		lda 	Const_Base+1,y
		sta 	NSMantissa1+1,x
		lda 	Const_Base+2,y
		sta 	NSMantissa2+1,x
		lda 	Const_Base+3,y 				; all four mantissa bytes are value now
		sta 	NSMantissa3+1,x
		lda 	Const_Base+4,y
		sta 	NSExponent+1,x
		lda 	Const_Base+5,y 				; and the sign, in a byte of its own
		sta 	NSStatus+1,x
		ply
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		log.asm
;		Purpose:	Log function.
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculate LOG(x)
;
; ************************************************************************************************

FloatLogarithm: 	
	
		lda 	NSStatus,x 					; check > 0
		bmi 	_ULRange
		jsr 	FloatIsZero
		beq 	_ULRange
		jsr 	FloatNormalise 				; put into FP mode.

		;
		;		LOG(1) has to be EXACTLY 0, and the general path below cannot deliver that. It
		;		computes log(f) + k*log(2); for x=1 those are -log(2) and +log(2), so the answer
		;		is the difference of two nearly equal numbers and comes out only as exactly as
		;		the polynomial is exact at the very END of its fitted interval (f = 0.5, k = 1).
		;		It was not: LOG(1) returned 3.2277181E-10 where stock X16 BASIC gives 0. Every
		;		other logarithm measured against stock already agreed, so special-case the one
		;		value rather than disturb the polynomial.
		;
		;		Normalised, the mantissa sits in [2^31,2^32), so 1.0 is the ONLY value with
		;		mantissa $80000000 and exponent -31 -- this is an exact identity test.
		;
		;		Deliberately NOT FloatCompare: that ignores the low 12 bits of the difference
		;		(compare.asm calls it "almost equal", 1 part in ~500,000), so it would also
		;		swallow everything just either side of 1 and return 0 for logarithms that are
		;		genuinely non-zero -- trading a wrong answer at one point for wrong answers
		;		across a whole neighbourhood.
		;
		lda 	NSMantissa0,x
		ora 	NSMantissa1,x
		ora 	NSMantissa2,x
		bne 	_ULNotOne
		lda 	NSMantissa3,x
		cmp 	#$80
		bne 	_ULNotOne
		lda 	NSExponent,x
		cmp 	#(-31) & $FF
		bne 	_ULNotOne
		jsr 	FloatSetZero 				; LOG(1) = 0, exactly. Clears the sign too.
		clc
		rts
_ULNotOne:

		lda 	NSExponent,x 				; get power
		pha

		;
		;		Split the value as f x 2^k with f in [0.5,1), which is the range the polynomial is
		;		fitted over. Normalised, the mantissa is in [2^31,2^32), so f is the mantissa read
		;		with an exponent of -32 and k is the real exponent plus 32. It was -31/+31 while
		;		the mantissa normalised to bit 30 -- see FloatNormalise. The two errors very nearly
		;		cancel (log2(2f) = log2(f)+1) which is why this looked half-alive, but it fed the
		;		polynomial an argument outside the interval it is fitted on.
		;
		lda 	#(-32) & $FF 				; force into range 0.5 -> 1
		sta 	NSExponent,x


		.pushfloat Const_sqrt_half 			; add sqrt 0.5
		jsr 	FloatAdd


		txa 								; divide into sqrt 2.0
		tay
		iny
		jsr 	CopyFloatXY
		dex
		.pushfloat Const_sqrt_2
		inx

		jsr 	FloatDivide 				; if zero, error.
		bcs 	_ULRangePla

		jsr 	FloatNegate 				; subtract from 1
		inx
		lda 	#1
		jsr 	FloatSetByte
		jsr 	FloatAdd

		jsr 	CoreLog
		jsr 	CompletePolynomial

		pla 								; add exponent
		clc
		adc 	#32 						; fix up, matching the -32 forced above

		pha
		bpl 	_LogNotNeg
		eor 	#$FF
		inc 	a		
_LogNotNeg:		
		inx 								; set byte and sign.
		jsr 	FloatSetByte

		pla
		and 	#$80
		sta 	NSStatus,x
		jsr 	FloatAdd

		.pushfloat Const_ln_e 			; * log2(e)
		jsr 	FloatMultiply
		clc
		rts

_ULRangePla:
		pla
_ULRange:
		sec
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		log_core.asm
;		Purpose:	Core LOG() polynomial
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculates LOG()
;
; ************************************************************************************************

CoreLog: 	
		lda 	#LogCoefficients & $FF
		ldy 	#LogCoefficients >> 8
		jmp 	CorePolySquared

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		pi.asm
;		Purpose:	PI constant
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									load PI
;
; ************************************************************************************************

FloatPI: 	
		.pushfloat Const_pi
		clc
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		power.asm
;		Purpose:	Power operator
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;								calculate S[0] ^ S[1]
;
; ************************************************************************************************

FloatPower:
		dex 							; S[X] = base, S[X+1] = exponent

;
;		x^0 is 1 for every x, 0^0 included -- which is what X16 BASIC answers.
;
		lda 	NSMantissa0+1,x
		ora 	NSMantissa1+1,x
		ora 	NSMantissa2+1,x
		ora 	NSMantissa3+1,x
		beq 	_FPWOne

;
;		0^n for nonzero n is 0. The logs below cannot do this at all -- log(0)
;		fails -- so this used to raise OUT OF RANGE where X16 BASIC just says 0.
;
		jsr 	FloatIsZero
		beq 	_FPWZero

;
;		A WHOLE exponent is done by repeated multiplication, which is EXACT.
;		exp(y*log x) is not: the round trip loses 7-8 bits, so 2^8 came back as
;		256.0000026 and 2^32 was 176 too large. Any program using 2^n as a bit mask
;		or an exact divisor was silently wrong -- the MD5 in testing/ slices a
;		64-bit length with 2^(8*J) and produced a wrong digest because of it.
;
;		Test for wholeness on a COPY in S[X+2]: FloatFractionalPart works on the
;		absolute value, which is exactly what the test wants. S[X+1] is left alone
;		so the logs path can still have the original exponent.
;
		inx 							; X = exponent
		txa
		tay
		iny 							; Y = scratch
		jsr 	CopyFloatXY
		inx 							; X = scratch
		jsr 	FloatFractionalPart
		jsr 	FloatIsZero 			; Z set (A = 0) if the exponent was whole
		dex
		dex 							; back to the base -- which trashes Z, so
		cmp 	#0 						; retest the A that FloatIsZero left
		bne 	_FPWUseLogs

;
;		Whole. Take the magnitude only if it fits one mantissa byte, the same shape
;		check FloatExponent makes. 256 and over cannot give a representable answer
;		for any |base| > 1 anyway, and for |base| < 1 the logs are the right tool.
;
		inx
		txa
		tay
		iny
		jsr 	CopyFloatXY 			; exponent -> scratch again
		inx
		jsr 	FloatIntegerPart
		dex
		dex

		lda 	NSMantissa1+2,x 		; anything above the low byte means >= 256
		ora 	NSMantissa2+2,x
		ora 	NSMantissa3+2,x
		ora 	NSExponent+2,x
		bne 	_FPWUseLogs
		lda 	NSMantissa0+2,x
		beq 	_FPWUseLogs 			; a zero exponent was handled above; belt and braces
		sta 	powCount

		lda 	NSStatus+1,x 			; which way to go at the end, while the
		sta 	powNegative 			; exponent is still untouched

;
;		The accumulator has to finish in S[X], where the base is now, so stash the
;		base up in S[X+3] and start S[X] at 1. S[X+3] is needed because
;		FloatMultiply SHIFTS ITS MULTIPLICAND to bits and leaves S[X+1] destroyed,
;		so the base has to be handed to it fresh every time round. S[X+2] is its
;		scratch. That is the same three slots above X the logs path already used.
;
		txa
		tay
		iny
		iny
		iny
		jsr 	CopyFloatXY 			; base -> S[X+3]
		lda 	#1
		jsr 	FloatSetByte 			; S[X] = 1

_FPWMulLoop:
		txa 							; Y = S[X+1], the multiplicand slot
		tay
		iny
		inx 							; X = S[X+3], where the base is kept
		inx
		inx
		jsr 	CopyFloatXY 			; refresh the multiplicand
		dex 							; X = S[X+1], so FloatMultiply's own dex
		dex 							; lands on the accumulator
		jsr 	FloatMultiply 			; S[X] *= S[X+1], returns X = accumulator
		dec 	powCount
		bne 	_FPWMulLoop

		lda 	powNegative
		bmi 	_FPWReciprocal
		clc
		rts

;
;		x^-n = 1/(x^n). Move the power up and divide one by it; FloatDivide reports
;		a zero divisor in carry, which is the answer for 0^-n.
;
_FPWReciprocal:
		txa
		tay
		iny
		jsr 	CopyFloatXY 			; x^n -> S[X+1]
		lda 	#1
		jsr 	FloatSetByte 			; S[X] = 1
		inx
		jmp 	FloatDivide 			; S[X] = 1 / S[X+1], and its carry is ours

_FPWOne:
		lda 	#1
		jsr 	FloatSetByte
		clc
		rts

_FPWZero:
		jsr 	FloatSetZero
		clc
		rts

;
;		Fractional exponent: the original exp(y * log x). This needs a positive
;		base, log() failing otherwise -- X16 BASIC refuses a fractional power of a
;		negative number too.
;
_FPWUseLogs:
		txa 							; copy 0 to 2, so we can process it
		tay
		iny
		iny
		jsr 	CopyFloatXY

		inx 							; 2 = Log(0)
		inx

		jsr 	FloatLogarithm
		bcs 	_FPWExit

		jsr 	FloatMultiply			; Multiply by original 1, into 1.

		txa 							; copy to slot 0
		tay
		dey
		jsr 	CopyFloatXY

		dex  							; Exponent code.

		jsr 	FloatExponent
_FPWExit:
		rts

		.send 	code

		.section storage
powCount: 									; whole exponent still to multiply in
		.fill 	1
powNegative: 								; sign of the exponent (bit 7)
		.fill 	1
		.send storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		sin.asm
;		Purpose:	Sine function.
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculate SIN(x)
;
; ************************************************************************************************

FloatSine:
		lda 	NSStatus,x 					; save sign
		pha
		stz 	NSStatus,x 					; make +ve

		.pushfloat Const_1Div2Pi 			; divide by 2*Pi

		jsr 	FloatMultiply 
		jsr 	FloatFractionalPart 		; take the fractional part

		;
		;		Quadrant split on the normalised exponent. The mantissa is in [2^31,2^32) now, so
		;		these are one lower than they were: 0.25-0.5 is exponent -33 ($DF, was $E0) and
		;		0.75 is mantissa $C0000000 (was $60000000) -- see FloatNormalise.
		;
		lda 	NSExponent,x 				; check exponent
		cmp 	#$DF 						; < $DF exponent : 0-0.25
		bcc 	_USProcessExit
		beq 	_USSubtractFromHalf 		; = $DF exponent : 0.25-0.5
		lda 	NSMantissa3,x 				; if > 0.75 which is $C0000000:$E0
		cmp 	#$C0
		bcs 	_USSubtractOne
_USSubtractFromHalf:						; 0.25 - 0.75 calculate 0.5-x
		.pushfloat Const_half 				; so calculate x-0.5
		jsr 	FloatSubtract
		jsr 	FloatNegate 				; then negate it
		bra 	_USProcessExit 				; and exit

_USSubtractOne:								; 0.75 - 1.0 calculate x - 1
		inx
		lda 	#1
		jsr 	FloatSetByte
		jsr 	FloatSubtract

_USProcessExit:
		jsr 	CoreSine
		jsr 	CompletePolynomial
		pla 								; restore sign and apply
		eor 	NSStatus,x
		sta 	NSStatus,x
		clc
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		sin_core.asm
;		Purpose:	Core SIN() polynomial
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculates SIN()
;
; ************************************************************************************************

CoreSine: 	
		lda 	#SinCoefficients & $FF
		ldy 	#SinCoefficients >> 8

; ************************************************************************************************
;
;					Do the x^2 polynomials (e.g. all other than EXP())
;
; ************************************************************************************************

CorePolySquared:
		pha 								; save coefficient table
		phy

		txa 								; copy X to +1, +2
		tay
		iny
		jsr 	CopyFloatXY
		iny
		jsr 	CopyFloatXY
		inx 								; point to the pair and put x^2 on stack
		inx
		jsr 	FloatMultiply
		ply 								; coefficient table back.
		pla
		jsr 	CalculateHornerPolynomial
		txa 								; copy back to slot #1
		tay
		dey
		jsr	 	CopyFloatXY		
		dex 								; point at result
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		sqr.asm
;		Purpose:	Square root function.
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculate SQR(x)
;
; ************************************************************************************************

FloatSquareRoot:
		jsr 	FloatIsZero 				; SQR(0) = 0. This routine computes the root as
		beq 	_FSQZero 					; exp(0.5*ln(x)), but ln(0) is undefined so
		;									; FloatLogarithm errors on 0 -- special-case it here,
		;									; matching interpreted BASIC (SQR(0)=0, SQR(-x)=error).
		jsr 	FloatLogarithm
		bcs 	_FSQExit
		dec 	NSExponent,x
		jsr 	FloatExponent
		clc
_FSQExit:
		rts
_FSQZero:
		jsr 	FloatSetZero 				; canonical +0 in slot X
		clc 								; CC = success
		rts

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		tan.asm
;		Purpose:	Tangent function.
;		Created:	11th April 2023
;		Reviewed: 	No
;		Author : 	Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;									calculate TAN(x)
;
; ************************************************************************************************

FloatTangent: 	
		phx
		txa 								; sin -> +1
		tay
		iny
		jsr 	CopyFloatXY
		inx
		jsr 	FloatSine 				
		dex

		txa 								; cos -> +2
		tay
		iny
		iny
		jsr 	CopyFloatXY		
		inx
		inx
		jsr 	FloatCosine 				

		jsr 	FloatDivide 				; calculate sin/cos
		bcs 	_FTExit 					; divide by zero

		txa 								; copy result down.
		tay
		dey
		jsr 	CopyFloatXY 				

		clc
_FTExit:
		plx	
		rts		


		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
