# *******************************************************************************************
#
#		Name :		gen_err_tokens.py
#		Purpose :	Keyword text for GPC.ERR's detokeniser, as a BASL include
#		Usage :		python source/gpc/gen_err_tokens.py [out.INC.BL]
#
# *******************************************************************************************

import os,re,sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__),"..",".."))
sys.path.insert(0,os.path.join(ROOT,"source","common-scripts"))
from c64tokens import C64TokenStore

GPB     = os.path.join(ROOT,"GPC-BASIC","GPB.INC.BL")
#		The tracked copy, and the one BASLOAD reads: an #INCLUDE resolves on the emulator
#		drive, which is GPC-BASIC-TOOLS-SRC/GPC.ERR/.
DEFAULT = [os.path.join(ROOT,"GPC-BASIC","ERRTOKEN.INC.BL"),
		   os.path.join(ROOT,"GPC-BASIC-TOOLS-SRC","GPC.ERR","GPC-BASIC","ERRTOKEN.INC.BL")]

#
#		The GP.* set as BASLOAD sees it. The #TOKEN lines are what tokenises a source, so they
#		are the authority; c64tokens.py carries its own copy and the two must agree.
#
def readTokenLines():
	found = {}
	for line in open(GPB,encoding="utf-8",errors="replace"):
		m = re.match(r"^#TOKEN\s+(\S+)\s+(\d+)\s*$",line.strip())
		if m:
			found[int(m.group(2))] = m.group(1).upper()
	return found

def main(targets):
	store   = C64TokenStore()
	declared = readTokenLines()
	byID    = store.idToToken

	#		Sorted by id. GP.BSTRSET is listed beside GP.BSTR in c64tokens.py, out of id order.
	inStore = {i:byID[i] for i in sorted(byID) if 0xCE01 <= i <= 0xCE7F}
	if inStore != declared:
		out = sorted(set(declared.items()) ^ set(inStore.items()))
		raise SystemExit("#TOKEN lines and c64tokens.py disagree: {0}".format(out))

	single = sorted(i for i in byID if i < 0x100)
	prefix = sorted(i for i in byID if i >= 0xCE00)
	stray  = [i for i in byID if i not in single and i not in prefix]
	if stray:
		raise SystemExit("token ids outside both ranges: {0}".format(stray))

	lowBase,lowTop = min(single),max(single)
	hiBase,hiTop   = min(prefix) & 0xFF,max(prefix) & 0xFF

	text = []
	w = text.append
	w("## ***********************************************************************")
	w("## **  ERRTOKEN.INC.BL -- BASIC keyword text, one string a token number.")
	w("## **")
	w("## **  GENERATED by source/gpc/gen_err_tokens.py out of the #TOKEN lines in")
	w("## **  GPC-BASIC/GPB.INC.BL and the stock tables in")
	w("## **  source/common-scripts/c64tokens.py. An edit here is lost on the next run.")
	w("## **")
	w("## **      ERR.TOKEN.PLAIN     a single byte token, index = byte - ERR.PLAIN.FIRST")
	w("## **      ERR.TOKEN.SHIFTED   a $CE pair, index = second byte - ERR.SHIFTED.FIRST")
	w("## **")
	w("## **  A slot no keyword uses is an empty string, which is what tells an unknown")
	w("## **  token from a real one. An index outside a group reads the next group's text,")
	w("## **  so a caller range checks the byte against BASE and TOP first.")
	w("## **")
	w("## **  Claim ERR.TOKENBANK before the first GP.BSTR.")
	w("## ***********************************************************************")
	w("#IFNDEF ERR.TOKENBANK")
	w("#DEFINE ERR.TOKENBANK 61")
	w("#ENDIF")
	w("")
	w("#DEFINE ERR.PLAIN.FIRST {0}".format(lowBase))
	w("#DEFINE ERR.PLAIN.LAST {0}".format(lowTop))
	w("#DEFINE ERR.SHIFTED.FIRST {0}".format(hiBase))
	w("#DEFINE ERR.SHIFTED.LAST {0}".format(hiTop))
	w("")

	for name,base,top,shift in (("ERR.TOKEN.PLAIN",lowBase,lowTop,0),
								("ERR.TOKEN.SHIFTED",hiBase,hiTop,0xCE00)):
		w("GP.BANKEDSTR ERR.TOKENBANK {0}".format(name))
		for n in range(base,top+1):
			keyword = byID.get(n+shift,"")
			if '"' in keyword:
				raise SystemExit("keyword {0} carries a quote".format(keyword))
			w('  "{0}"'.format(keyword))
		w("GP.ENDBANKEDSTR")
		w("")

	body = "\n".join(text)
	for target in targets:
		open(target,"wb").write(body.encode("ascii"))
	print("  gen_err_tokens: OK -- {0} ({1} bytes, {2} slots, {3} keywords)".format(
		", ".join(os.path.relpath(t,ROOT).replace("\\","/") for t in targets),
		len(body),(lowTop-lowBase+1)+(hiTop-hiBase+1),len(byID)))

if __name__ == "__main__":
	main(sys.argv[1:] if len(sys.argv) > 1 else DEFAULT)
