# *******************************************************************************************
# *******************************************************************************************
#
#       Name :      genasm.py
#       Purpose :   65C02 opcode tables for GP.ASM, the inline assembler.
#       Date :      30th August 2026
#       Author :    Steven De George SR
#
#		Writes source/generated/gpasmtable.asm -- two tables the assembler searches at
#		COMPILE time, so every byte of them is compiler space and costs a compiled program
#		nothing. build.py picks the file up like any other .asm under source/.
#
#		BBR/BBS/RMB/SMB are deliberately absent. They are Rockwell additions with a
#		four-character mnemonic ending in a bit number and, for BBR/BBS, a two-operand
#		"zp,rel" mode found nowhere else -- all of which the parser would have to grow a
#		special case for, to assemble instructions nothing on this machine uses.
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys

#
#		Addressing modes. These constants are emitted into the .asm as well, so the
#		assembler and this table can never disagree about what a number means.
#
MODES = ["IMP","IMM","ZP","ZPX","ZPY","ABS","ABX","ABY","IND","IZX","IZY","IZP","IAX","REL"]

#
#		The instruction set, mnemonic : mode/opcode pairs. IMP covers "no operand at all"
#		and the accumulator forms (ASL A, INC A) alike -- both assemble to one byte.
#
OPCODES = """
ADC IMM 69 ZP 65 ZPX 75 ABS 6D ABX 7D ABY 79 IZX 61 IZY 71 IZP 72
AND IMM 29 ZP 25 ZPX 35 ABS 2D ABX 3D ABY 39 IZX 21 IZY 31 IZP 32
ASL IMP 0A ZP 06 ZPX 16 ABS 0E ABX 1E
BCC REL 90
BCS REL B0
BEQ REL F0
BIT IMM 89 ZP 24 ZPX 34 ABS 2C ABX 3C
BMI REL 30
BNE REL D0
BPL REL 10
BRA REL 80
BRK IMP 00
BVC REL 50
BVS REL 70
CLC IMP 18
CLD IMP D8
CLI IMP 58
CLV IMP B8
CMP IMM C9 ZP C5 ZPX D5 ABS CD ABX DD ABY D9 IZX C1 IZY D1 IZP D2
CPX IMM E0 ZP E4 ABS EC
CPY IMM C0 ZP C4 ABS CC
DEC IMP 3A ZP C6 ZPX D6 ABS CE ABX DE
DEX IMP CA
DEY IMP 88
EOR IMM 49 ZP 45 ZPX 55 ABS 4D ABX 5D ABY 59 IZX 41 IZY 51 IZP 52
INC IMP 1A ZP E6 ZPX F6 ABS EE ABX FE
INX IMP E8
INY IMP C8
JMP ABS 4C IND 6C IAX 7C
JSR ABS 20
LDA IMM A9 ZP A5 ZPX B5 ABS AD ABX BD ABY B9 IZX A1 IZY B1 IZP B2
LDX IMM A2 ZP A6 ZPY B6 ABS AE ABY BE
LDY IMM A0 ZP A4 ZPX B4 ABS AC ABX BC
LSR IMP 4A ZP 46 ZPX 56 ABS 4E ABX 5E
NOP IMP EA
ORA IMM 09 ZP 05 ZPX 15 ABS 0D ABX 1D ABY 19 IZX 01 IZY 11 IZP 12
PHA IMP 48
PHP IMP 08
PHX IMP DA
PHY IMP 5A
PLA IMP 68
PLP IMP 28
PLX IMP FA
PLY IMP 7A
ROL IMP 2A ZP 26 ZPX 36 ABS 2E ABX 3E
ROR IMP 6A ZP 66 ZPX 76 ABS 6E ABX 7E
RTI IMP 40
RTS IMP 60
SBC IMM E9 ZP E5 ZPX F5 ABS ED ABX FD ABY F9 IZX E1 IZY F1 IZP F2
SEC IMP 38
SED IMP F8
SEI IMP 78
STA ZP 85 ZPX 95 ABS 8D ABX 9D ABY 99 IZX 81 IZY 91 IZP 92
STP IMP DB
STX ZP 86 ZPY 96 ABS 8E
STY ZP 84 ZPX 94 ABS 8C
STZ ZP 64 ZPX 74 ABS 9C ABX 9E
TAX IMP AA
TAY IMP A8
TRB ZP 14 ABS 1C
TSB ZP 04 ABS 0C
TSX IMP BA
TXA IMP 8A
TXS IMP 9A
TYA IMP 98
WAI IMP CB
""".strip().split("\n")

#
#		Three letters into fifteen bits, A=1..Z=26. The assembler packs the mnemonic it has
#		just read the same way and compares two bytes, which is both smaller and faster than
#		comparing text.
#
def pack(m):
	assert len(m) == 3, m
	v = 0
	for c in m:
		v = (v << 5) | (ord(c) - 64)
	return v

mnemonics = []
entries = []
for line in OPCODES:
	p = line.split()
	name = p[0]
	first = len(entries)
	for i in range(1,len(p),2):
		assert p[i] in MODES, (name,p[i])
		entries.append((p[i],int(p[i+1],16)))
	mnemonics.append((name,pack(name),first,len(entries)-first))

assert len(entries) < 256, "mode entry index no longer fits a byte"

h = open(os.path.join("source","generated","gpasmtable.asm"),"w")
h.write(";\n;\tThis file is automatically generated by scripts/genasm.py -- do not edit.\n")
h.write(";\n;\t65C02 opcode tables for GP.ASM. Compiler space only: everything here lives\n")
h.write(";\tabove ObjectBase and is thrown away when the object code is written.\n;\n")
for i,m in enumerate(MODES):
	h.write("AMODE_{0:<4}= {1}\n".format(m,i))
h.write("AMODE_COUNT = {0}\n".format(len(MODES)))
h.write("\n\t\t.section code\n\n")
h.write(";\n;\tOne entry per mnemonic, 4 bytes: packed name lo/hi, first mode entry, count.\n")
h.write(";\tTerminated by a zero packed name. {0} mnemonics.\n;\n".format(len(mnemonics)))
h.write("AsmMnemonicTable:\n")
for name,packed,first,count in mnemonics:
	h.write("\t\t.byte\t${0:02x},${1:02x},{2},{3}\t\t; {4}\n".format(packed & 255,packed >> 8,first,count,name))
h.write("\t\t.byte\t$00,$00\t\t\t\t; end of table\n")
h.write("\n;\n;\tOne entry per addressing mode of every mnemonic, 2 bytes: mode, opcode.\n")
h.write(";\t{0} entries.\n;\n".format(len(entries)))
h.write("AsmModeTable:\n")
for mode,op in entries:
	h.write("\t\t.byte\tAMODE_{0},${1:02x}\n".format(mode,op))
h.write("\n\t\t.send code\n")
h.close()
print("  genasm: {0} mnemonics, {1} opcode entries".format(len(mnemonics),len(entries)))
