# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		constants.py
#		Purpose :	Create decimal scalar table
#		Date :		11th April 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math

#
#		Table of 10^1 .. 10^POWER_COUNT, five bytes each (4 byte mantissa + exponent), used by
#		FloatScalePower10 to scale a literal's digits. Two things about it matter, and both are
#		load bearing:
#
#		1)	The powers are POSITIVE, and a literal like 0.5 is scaled by DIVIDING by 10^1 rather
#			than by multiplying by a tabulated 10^-1. 10^-n can never be exact - 1/10 is not a
#			binary fraction - and the old table's error was LOW, so 5 x 10^-1 came out as
#			0.4999999998 even though 0.5 is exactly representable. 5/10 lands on it exactly.
#
#		2)	The entries are plain INTEGERS - mantissa = 10^n, exponent 0 - not normalised floats.
#			FloatMultiply has a fast path for integer x integer that is exact whenever the product
#			fits, and it returns an integer. A normalised operand instead forces the float path,
#			whose shift-add loop truncates, and returns a float. Both compute 9 x 10^5 = 900000
#			correctly, but only the integer one PRINTS as "900000": the float printer is lossy
#			(it is what renders 3.14159 as "3.1415900"), so it showed 900000.0004882. Keeping the
#			table integral keeps whole-number literals whole. FloatDivide normalises its operands
#			itself, so the divide path does not care either way.
#
#		10^9 is the last power that fits in the 31 bit mantissa, which caps the table. Bigger
#		powers are applied a tableful at a time by FloatScalePower10.
#
POWER_COUNT = 9

f = open("source/generated/constants.asm","w")
f.write(";\n;\tThis file is automatically generated.\n;\n")
f.write(".section code\n")
f.write("FloatPower10TableSize = {0} ; entries: 10^1 .. 10^{0}\n".format(POWER_COUNT))
f.write("FloatPower10Table:\n")

for i in range(1,POWER_COUNT+1):
	#
	#		Exponent 0 means "the mantissa IS the value", so the entry is 10^i outright. Assert
	#		it still fits the signed 31 bit mantissa, so that raising POWER_COUNT past what the
	#		format can hold fails the build rather than quietly emitting a wrapped constant.
	#
	value = pow(10,i)
	assert value < pow(2,31), "10^{0} does not fit the mantissa".format(i)

	f.write("\t.dword ${0:08x} ; 10^{1} = {2}\n".format(value,i,value))
	f.write("\t.byte $00\n")

f.write(".send code\n")
f.close()
