# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		constants.py
#		Purpose :	Create decimal scalar table
#		Date :		11th April 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math
from floats import *

#
#		Entries are 10^-1 .. 10^-SCALAR_COUNT, five bytes each (4 byte mantissa + exponent).
#		FloatScalePower10 indexes this table and needs to know where it stops, so emit the
#		count rather than letting an assembler-side magic number drift out of step with it.
#
SCALAR_COUNT = 11

f = Float()
h = open("source/generated/constants.asm","w")
h.write(";\n;\tThis file is automatically generated.\n;\n")
h.write(".section code\n")
h.write("FloatScalarTableSize = {0} ; entries: 10^-1 .. 10^-{0}\n".format(SCALAR_COUNT))
h.write("FloatScalarTable:\n")
for i in range(1,SCALAR_COUNT+1):
	decimal = 1.0 / pow(10,i)
	ed = f.toFloat(decimal)
	h.write("\t.dword ${0:08x} ; {1}\n".format(ed[0],decimal))
	h.write("\t.byte ${0:02x}\n".format(ed[1]))
h.write(".send code\n")

h.close()