;
;	This file is automatically generated
;
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		00gpbase.asm
;		Purpose:	Marks the start of the GP.BASIC handler block.
;		Created:	18th August 2026
;
; ************************************************************************************************
; ************************************************************************************************
;
;		GPBase is the cut line. Everything from here to ObjectBase is GP.BASIC handler code and
;		nothing else, so a program that uses no GP keyword has its runtime written out as
;		$0801..GPBase instead of $0801..ObjectBase -- 2,560 bytes it never loads, and the same
;		again off the bottom of its workspace. See WriteObjectCode and compiler/gpscan.asm.
;
;		IT LIVES INSIDE gp.library, NOT IN A DIVIDER FILE, and that is the point: every link
;		line that pulls in gp.library gets the symbol automatically. A divider would have had to
;		be added to four separate link lines -- the runtime test build, gpc-rt, checkall and the
;		application -- and the one that got forgotten would have failed as an undefined symbol
;		somewhere unrelated.
;
;		THE LEADING ZEROS IN THE NAME ARE LOAD BEARING. build.py sorts by leafname and the sort
;		order IS the link order, so this file must sort ahead of every other file in this tree
;		or the label lands in the middle of the block it is supposed to open.
;
;		It declares no command marker, so it defines no opcode and takes no vector slot --
;		pcode.py walks straight past it and every existing token keeps its number. (Spelling the
;		marker out here would BREAK THE BUILD: pcode.py scans comments too, and a description of
;		one fails its assert as a malformed declaration.)
;
; ************************************************************************************************

		.section code

		;
		;		Page aligned, because WriteObjectCode's copy loop stops on a page boundary and
		;		the object code that lands here on reload must start on one. Costs up to 255
		;		bytes of padding in the compiler's own image, which sits above the cut and is
		;		thrown away anyway.
		;
		.align 	256
GPBase:

		.send code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		do.asm
;		Purpose:	GP.DO / GP.LOOP counted loop
;		Created:	16th August 2026
;		Reviewed: 	No
;		Author : 	Steven De George SR
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;								<Count> GP.DO ... GP.LOOP
;
;		A counted loop with NO loop variable, modelled on prog8's "repeat" and named after CBM
;		BASIC 7.0's DO/LOOP. That missing variable is the entire point: FOR/NEXT spends most of
;		its time on the index -- decoding an operand address, reading six iFloat32 bytes,
;		comparing against a terminal value and writing six bytes back -- and none of that exists
;		here. The counter lives in the frame itself and is a plain 16 bit decrement.
;
;		Everything it needs was already in the image and is already linked for FOR/NEXT/GOSUB:
;		GetInteger16Bit, StackOpenFrame, StackSaveCurrentPosition, StackLoadCurrentPosition,
;		StackCloseFrame and StackFindFrame. This file adds glue, not machinery, which is why the
;		whole construct costs well under a tenth of what FOR alone does.
;
; ************************************************************************************************

CommandXDo: ;; [gp.do]
		.entercmd
		lda 	#FRAME_LOOP 				; open the frame FIRST.
		jsr 	StackOpenFrame
		jsr 	StackSaveCurrentPosition 	; normalise to Y=0 and save the loop-back position.
		;
		;		Order matters and is not stylistic: StackOpenFrame uses zTemp0 as scratch for the
		;		frame size, so fetching the count before opening the frame would have it
		;		overwritten. GetInteger16Bit is therefore called last, and its result is consumed
		;		immediately.
		;
		jsr 	GetInteger16Bit 			; count => zTemp0, truncated to 16 bits
		ldy 	#4
		lda 	zTemp0
		sta 	(runtimeStackPtr),y
		iny
		lda 	zTemp0+1
		sta 	(runtimeStackPtr),y
		dex 								; throw the count
		ldy 	#0
		.exitcmd

; ************************************************************************************************
;
;									GP.LOOP : end of a GP.DO
;
; ************************************************************************************************

CommandXLoop: ;; [gp.loop]
		.entercmd
		;
		;		Same guard as NEXT: a well nested loop has its own frame already on top, so
		;		StackFindFrame would spend ~34 cycles finding what is under its nose. Any other
		;		byte -- a FOR or GOSUB frame, or the $FF fail marker that raises the structure
		;		error -- falls through to the general path exactly as before.
		;
		lda 	(runtimeStackPtr) 			; loop frame already on top ?
		cmp 	#FRAME_LOOP
		beq 	_CLOnTop
		lda 	#FRAME_LOOP
		jsr 	StackFindFrame
_CLOnTop:
		;
		;		MUST come before Y is touched, exactly as NEXT does it. On entry Y is the offset
		;		into the current code page, and the frame accesses below overwrite it -- so
		;		without this the position is simply lost. The loop-back path happens to survive
		;		(StackLoadCurrentPosition reloads codePtr AND zeroes Y), but the exit path's
		;		"ldy #0" would then resume at the START of the page rather than after GP.LOOP,
		;		and the VM runs off into whatever follows. That is a BRK into the monitor with no
		;		error message, which is exactly how this first showed up.
		;
		jsr 	FixUpY 						; normalise codePtr so Y is free to use
		;
		;		Decrement the 16 bit counter, exit when it REACHES zero. Post-tested, so the body
		;		has already run once by the time we get here and a count of n gives exactly n
		;		passes.
		;
		;		A counter of zero ON ENTRY therefore cannot be a counted loop winding down -- we
		;		close the frame the moment a decrement produces zero, so zero is never left behind
		;		on a live loop. That makes it unambiguous, and it is what a bare GP.DO compiles to
		;		(OptionalNumberCompile pushes 0 for an omitted argument): ZERO MEANS FOREVER, and
		;		it loops back without touching the counter at all.
		;
		ldy 	#4
		lda 	(runtimeStackPtr),y 		; counter low
		bne 	_CLDecLow 					; non-zero, so no borrow needed
		iny
		lda 	(runtimeStackPtr),y 		; counter high
		beq 	_CLBack 					; $0000 => loop forever
		dec 	a 							; borrow from the high byte
		sta 	(runtimeStackPtr),y
		dey
		lda 	#0 							; low was zero, so it becomes $FF below
_CLDecLow:
		dec 	a
		sta 	(runtimeStackPtr),y 		; Y is 4 on both paths
		bne 	_CLBack 					; low non-zero => counter cannot be zero
		ldy 	#5
		lda 	(runtimeStackPtr),y
		bne 	_CLBack 					; high non-zero => still running
		;
		jsr 	StackCloseFrame 			; counter hit zero, drop the frame and fall through
		ldy 	#0
		.exitcmd
_CLBack:
		jsr 	StackLoadCurrentPosition 	; back to the top of the body (sets Y = 0)
		.exitcmd

; ************************************************************************************************
;
;							GP.EXITDO : leave the innermost GP.DO early
;
;		The whole command is three instructions because both halves already exist. StackFindFrame
;		lands on the innermost GP.DO frame and DISCARDS everything stacked above it on the way, so
;		a FOR abandoned inside the loop is cleaned up for free -- and if there is no loop at all it
;		stops on the $FF marker and raises the structure error, which is the runtime backstop for
;		an EXITDO the compiler somehow let through. Y is the code pointer offset here and neither
;		StackFindFrame nor StackCloseFrame touches it (both use 65C02 zp INDIRECT, not
;		indirect-indexed), so the error address stays meaningful and PerformGOTO still finds its
;		operand where it expects it.
;
;		The operand is a branch offset with exactly the shape of a .goto's, filled in by
;		FixBranches, so the jump itself is literally the GOTO code.
;
; ************************************************************************************************

CommandXExitDo: ;; [.exitdo]
		.entercmd
		lda 	#FRAME_LOOP 				; innermost GP.DO frame, discarding anything above it
		jsr 	StackFindFrame
		jsr 	StackCloseFrame 			; drop it -- we are leaving the loop for good
		jmp 	PerformGOTO 				; and branch past the matching GP.LOOP

; ************************************************************************************************
;
;		0	GP.DO Marker 			[1]
;		1 	(unused)				[1]		so +2/+3 line up with FRAME_FOR, which is what
;		2 	Position for loop 		[2]		StackSave/LoadCurrentPosition hard-code
;		4	Counter, 16 bit 		[2]		$0000 = loop forever
;
; ************************************************************************************************

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;		16/08/26		Written.
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		gparrptr.asm
;		Purpose:	GP.ARRPTR -- the address of an array's element zero
;		Created:	17th August 2026
;		Reviewed: 	No
;		Author : 	Steven De George SR
;
;		This was gpsort.asm, and GP.SORT was the bulk of it. The sort left the GP block on
;		1st September 2026 and is GPC-BASIC/SORT.INC.BL now -- the same shell sort, the same
;		Ciura gaps, written in GP.ASM -- because the block is all or nothing and 408 of its
;		bytes were a sort that most programs never call. What is left is the 49 bytes that
;		hand an array's address over, which is what the module is built on: a BASL subroutine
;		cannot be passed an array.
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;						GP.ARRPTR(a()) -> the address of element ZERO
;
;		The escape hatch. It is for the jobs too specific to ever be keywords -- sprite
;		batching, array fill, checksum, min/max -- which can be written once as machine code
;		and driven with GP.CALL, or with a GP.ASM block, instead of each having to become its
;		own keyword or not exist. GP.SORT is now the first and largest example of exactly that.
;
;		It is AnyArrayCompile's path with the value RETURNED rather than consumed.
;
;		Returns base + variableStartPage*256 + 3, skipping the 3-byte header, so the answer is
;		element zero and not the count word. THE HEADER IS STILL THERE and is worth knowing
;		about: count low, count high, then the type byte, at -3, -2 and -1. SORT.INC.BL reads
;		its element count and rejects a float array from exactly those three bytes.
;
;		Stride is the caller's business: 2 bytes for a string (a pointer to its block) and 6
;		for a number.
;
;		Multi-dimensional arrays are REJECTED, because the elements are not a flat run -- they
;		are pointers to sub-levels, so an address into one would be used as data and corrupt
;		silently.
;
;		A subscript inside the parentheses is a syntax error by construction: AnyArrayCompile
;		demands the ")" immediately. GP.ARRPTR(A(3)) does not compile -- add 3*stride yourself.
;
;		SAME WARNING AS GP.STRPTR: the address routinely exceeds 32767, and BASIC's AND is 16-bit
;		SIGNED, so splitting it with "P AND 255" raises OUT OF RANGE. Use GP.HIBYTE / GP.LOBYTE,
;		or the long form H = INT(P/256) : L = P - H*256.
;
; ************************************************************************************************

UnaryGPArrPtr: ;; [!gp.arrptr]
		.entercmd
		phy
		lda 	NSMantissa0,x 				; the base arrives as an OFFSET, so the high byte
		sta 	zTemp0 						; needs variableStartPage adding to make it real
		lda 	NSMantissa1,x
		clc
		adc 	variableStartPage
		sta 	zTemp0+1
		;
		ldy 	#2 							; bit 7 of the type byte = sub-arrays below this level
		lda 	(zTemp0),y
		bmi 	_GAPBad
		;
		clc 								; step over the 3-byte header to element zero
		lda 	zTemp0
		adc 	#3
		sta 	NSMantissa0,x
		lda 	zTemp0+1
		adc 	#0
		sta 	NSMantissa1,x
		stz 	NSMantissa2,x 				; and retype it from an int16 reference to a plain
		stz 	NSMantissa3,x 				; number, exactly as GP.STRPTR does
		stz 	NSExponent,x
		stz 	NSStatus,x 					; NSSIFloat is $00, so this also clears the sign
		ply
		.exitcmd

_GAPBad:
		ply 								; code pointer back before raising, or the address in
		.error_index 						; the message is a fixed meaningless one

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;		17/08/26		Written, as gpsort.asm.
;		01/09/26		GP.SORT moved out of the block into GPC-BASIC/SORT.INC.BL. The file is
;						renamed for what is left of it, and the 15 bytes of gps* storage that
;						sat below $0801 went with the sort.
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		gpbstr.asm
;		Purpose:	GP.BSTR -- one string out of the GP.BANKEDSTR bank
;		Created:	7th September 2026
;		Reviewed: 	No
;		Author : 	Steven De George SR
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;					GP.BSTR(<group>, n) -> string n of that group, as a string
;
;		The read side of GP.BANKEDSTR (compiler/commands/gpbstr.asm). The text lives at $A000 in
;		a RAM bank and is fetched one item at a time, which is what lets a GUI program's several
;		thousand bytes of literal text out of low RAM entirely.
;
;		IT TAKES ONE ARGUMENT BY THE TIME IT RUNS, not two. The group name is resolved at compile
;		time to a constant base and the compiler emits an ADD, so what reaches the stack is a
;		single flat index. That keeps the addition out of here -- it costs one p-code byte at the
;		call site and saves the handler doing it -- and it is why no letter of the group name
;		appears anywhere in this file.
;
;		THE BANK LAYOUT, all offsets from $A000:
;
;			+0		string count, 16 bit
;			+2		count * 16-bit offsets, each the offset of one record from $A000
;			...		the records, [length][characters] back to back
;
;		The count is not read here. The compiler knows every index it emits and there is nothing
;		a program can do at run time to produce one out of range, so a check would cost bytes on
;		every call to catch nothing.
;
;		IT PUTS THE CALLER'S BANK BACK, and that is not tidiness -- it is what lets a GP.BANKED
;		region call this. Control returns to $A000+n in the region's own bank, so leaving the text
;		bank selected would fetch the next instruction out of the wrong one: a silent hang nowhere
;		near the call. Same reason PEEK saves and restores it (x16_peekpoke.asm), and the same
;		mistake STASH made until it was fixed.
;
;		THE INDEX COMES OUT OF THE SLOT BEFORE StringAllocTemp IS CALLED, because that routine
;		writes the allocated block's address into NSMantissa0/1,x -- the very bytes the index
;		arrived in. Read it first or it is gone.
;
;		THE TEXT IS IN ONE OF SIXTEEN BANKS AND THE CONSTANT SAYS WHICH. The top four bits of the
;		index are a SLOT, and GPBSTRBANKS turns the slot into the RAM bank -- so a program's text
;		is no longer capped at one 8K bank, and it costs the call site nothing at all: the
;		constant was already being pushed and the bits were already spare.
;
;		TWELVE BITS ARE LEFT FOR THE INDEX, and they cap nothing. An 8K bank holds at most 2,730
;		strings -- two directory bytes and a length byte each -- so the compiler's 8K region check
;		stops a bank long before 4,096 could.
;
;		GPBSTRBANKS IS WRITTEN BY THE COMPILER AND READ WHERE IT LIES: it is the top sixteen
;		bytes of the program's bootstrap extension page, filled in as that page is built. The
;		runtime is SHARED, so one image serves every program and cannot know which banks any of
;		them chose -- and it is a FIXED address from common.inc, not a label in this file,
;		because this file is linked into two images with gp.library at opposite ends and a label
;		lands somewhere different in each. See the note beside GPBSTRBANKS.
;
; ************************************************************************************************

UnaryGPBStr: ;; [!gp.bstr]
		.entercmd
		phy
		;
		;		THE INDEX GOES THROUGH GetInteger16Bit, not straight out of NSMantissa0/1. The
		;		argument arrives as whatever the expression produced -- a constant base plus a
		;		FOR variable is a float -- and reading a float's mantissa as an address is a
		;		crash a long way from here. GP.ARRPTR can read the slot raw because its argument
		;		is an array reference and is int16 by construction; this one cannot.
		;
		jsr 	GetInteger16Bit 			; slot<<12 + the index within that slot's bank, into zTemp0
		;
		;		THE SLOT COMES OFF THE TOP FIRST, because everything below wants the index alone.
		;
		;		AND X GOES ON THE STACK ACROSS IT, because X is the EVALUATION STACK SLOT -- the same
		;		X the note above says StringAllocTemp writes NSMantissa0/1,x with. Indexing the bank
		;		table with it destroys it, and the value it destroys it with is the slot: text in the
		;		program's SECOND text bank then lands in the right place by coincidence and text in
		;		the first does not, which is what it did.
		;
		phx
		lda 	zTemp0+1
		lsr 	a
		lsr 	a
		lsr 	a
		lsr 	a
		tax
		lda 	GPBSTRBANKS,x 				; ...and which RAM bank that slot's text is in
		sta 	gpbsBank
		plx
		lda 	zTemp0+1
		and 	#$0F 						; leaving twelve bits of index
		sta 	zTemp0+1
		;
		;		The directory entry for it: $A002 + index*2.
		;
		asl 	zTemp0
		rol 	zTemp0+1
		clc
		lda 	zTemp0
		adc 	#2
		sta 	zTemp0
		lda 	zTemp0+1
		adc 	#$A0
		sta 	zTemp0+1
		;
		lda 	SelectRAMBank 				; from here to the restore below, $A000-$BFFF is text
		sta 	gpbsSaved
		lda 	gpbsBank
		sta 	SelectRAMBank
		;
		;		...and the record it points at. The stored offset is from $A000 and a bank is 8K,
		;		so its high byte is 0..$1F and adding $A0 is the whole of the relocation.
		;
		lda 	(zTemp0)
		sta 	gpbsRec
		ldy 	#1
		lda 	(zTemp0),y
		clc
		adc 	#$A0
		sta 	gpbsRec+1
		;
		;		THE POINTER IS PARKED OUT OF ZERO PAGE ACROSS StringAllocTemp, which is entitled
		;		to whatever scratch it likes -- and then put back. The length is read first for
		;		the same reason, and because StringAllocTemp overwrites the very stack slot the
		;		index arrived in with the block's address.
		;
		lda 	gpbsRec
		sta 	zTemp1
		lda 	gpbsRec+1
		sta 	zTemp1+1
		lda 	(zTemp1)
		sta 	gpbsLen
		jsr 	StringAllocTemp 			; A = length. Allocates AND retypes the slot to a string
		lda 	gpbsRec
		sta 	zTemp1
		lda 	gpbsRec+1
		sta 	zTemp1+1
		;
		lda 	gpbsLen
		sta 	(zsTemp)
		beq 	_GBSRestore 				; an empty string is a length and nothing else
		tay
_GBSCopy:
		lda 	(zTemp1),y
		sta 	(zsTemp),y
		dey
		bne 	_GBSCopy 					; y = 0 is the length byte, already written

_GBSRestore:
		lda 	gpbsSaved
		sta 	SelectRAMBank
		ply
		.exitcmd

		.send 	code

		.section storage
gpbsSaved: 									; the caller's bank, held across the fetch
		.fill 	1
gpbsBank: 									; the slot's text bank, read before the index is unpacked
		.fill 	1
gpbsLen: 									; the record's length, held across StringAllocTemp
		.fill 	1
gpbsRec: 									; the record's address, held across it too -- zero page
		.fill 	2 							; is not ours to keep over a call
		.send 	storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;		07/09/26		Written.
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		gpcall.asm
;		Purpose:	GP.CALL and the register readers GP.A / GP.X / GP.Y / GP.C
;		Created:	16th August 2026
;		Reviewed: 	No
;		Author : 	Steven De George SR
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;						<Addr> <A> <X> <Y> <C> GP.CALL
;
;		Call machine code with the registers set from arguments, and read the results back with
;		GP.A / GP.X / GP.Y / GP.C. What it removes is the POKE/SYS/PEEK dance:
;
;			POKE $30C,65 : POKE $30D,0 : SYS 49152 : A=PEEK($30C)      becomes
;			GP.CALL 49152,65,0 : A=GP.A
;
;		It shares SYS's storage at $030C-$030F deliberately, so the two interoperate and PEEK
;		still reads what either of them left behind.
;
;		A, X, Y and C are all optional and DEFAULT TO ZERO. Zero needs no sentinel -- there is
;		nothing here that has to test for "omitted", because an unspecified register genuinely is
;		0 -- and 0 compiles to a one byte short constant, so omitting costs less than supplying.
;		Contrast GP.STASH's geometry, where 255 had to be a real sentinel.
;
;		CARRY IN is set with LSR rather than PLP. SYS pushes a whole status byte and PLPs it,
;		which also writes I and D -- clearing the interrupt disable inside a routine that had set
;		it. LSR moves bit 0 of the argument into carry and touches nothing else, and LDA/LDX/LDY
;		do not affect carry, so the registers can be loaded afterwards without disturbing it.
;
; ************************************************************************************************

CommandGPCall: ;; [!gp.call]
		.entercmd
		phy 								; Y is the code pointer offset -- needed after the call
		;
		;		Arguments were pushed left to right, so TOS is the LAST of them.
		;
		lda 	NSMantissa0,x 				; C -- parked in SYS_Reg_S, which the result overwrites
		sta 	SYS_Reg_S
		dex
		lda 	NSMantissa0,x 				; Y
		sta 	SYS_Reg_Y
		dex
		lda 	NSMantissa0,x 				; X
		sta 	SYS_Reg_X
		dex
		lda 	NSMantissa0,x 				; A
		sta 	SYS_Reg_A
		dex
		;
		jsr 	FloatIntegerPart 			; the address itself
		lda 	NSMantissa0,x
		sta 	zTemp0
		lda 	NSMantissa1,x
		sta 	zTemp0+1
		dex 								; drop the address
		phx 								; the float stack pointer is X, and X is an argument
		;
		lda 	SYS_Reg_S 					; carry from bit 0, leaving I and D alone
		lsr 	a
		ldx 	SYS_Reg_X 					; LD* do not affect carry
		ldy 	SYS_Reg_Y
		lda 	SYS_Reg_A
		jsr 	_CGCCall
		;
		php 								; results, status included, for GP.C
		sta 	SYS_Reg_A
		stx 	SYS_Reg_X
		sty 	SYS_Reg_Y
		pla
		sta 	SYS_Reg_S
		;
		plx
		ply
		.exitcmd

_CGCCall:
		jmp 	(zTemp0)

; ************************************************************************************************
;
;					GP.A / GP.X / GP.Y / GP.C -- read back what GP.CALL returned
;
;		Value words taking no argument, exactly as ST/MX/MY are, so they push a value rather than
;		consuming one -- hence the INX. Left UNSHIFTED on purpose: these are read inside loops
;		where 41 cycles against 58 and one byte against two is the whole point of having them
;		instead of PEEK. GP.CALL itself is shifted, like SYS, because a machine code call dwarfs
;		its own dispatch.
;
; ************************************************************************************************

UnaryGPA: ;; [gp.a]
		.entercmd
		lda 	SYS_Reg_A
GPRegPush:
		inx 								; reads as a value, so it pushes one
		jsr 	FloatSetByte
		.exitcmd

UnaryGPX: ;; [gp.x]
		.entercmd
		lda 	SYS_Reg_X
		bra 	GPRegPush

UnaryGPY: ;; [gp.y]
		.entercmd
		lda 	SYS_Reg_Y
		bra 	GPRegPush

UnaryGPC: ;; [gp.c]
		.entercmd
		lda 	SYS_Reg_S 					; carry is bit 0 of the status byte
		and 	#1
		bra 	GPRegPush

		.send 	code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;		16/08/26		Written.
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		gpdraw.asm
;		Purpose:	GP.BOX / GP.FILL / GP.PRINTAT -- direct-to-VERA text drawing
;		Created:	17th August 2026
;		Reviewed: 	No
;		Author : 	Steven De George SR
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;			GP.BOX x,y,w,h [,style] [,col]      GP.FILL x,y,w,h,char [,col]
;			GP.PRINTAT x,y,text$ [,col]
;
;		The fast path for text-mode UI. These are not a restatement of LOCATE and PRINT -- they
;		write STRAIGHT INTO VERA. GPC's own character output makes TWO KERNAL calls for every
;		single character (x16_printchar.asm: CLRCHN to select the channel, then BSOUT, and BSOUT
;		itself carries scroll checks, quote mode and cursor handling). Here a cell is two stores
;		to VRAMData0, with the auto-increment walking the row.
;
;		THE TWO WORLDS ARE SEPARATE AND THAT IS DELIBERATE. Nothing here calls the KERNAL, so
;		nothing here moves the KERNAL cursor: a plain PRINT after a GP.PRINTAT resumes where the
;		KERNAL still thinks the cursor is, NOT after the text just drawn. Mixing them will
;		surprise someone at least once, which is why it is said here and in GPB.INC.BL.
;
;		THE OPTIONAL COLOUR DEFAULTS TO WHAT "COLOR" LAST SET. The KERNAL keeps the current text
;		colour in $0376 packed as (background << 4) | foreground -- which is byte for byte the
;		VERA attribute format, so the default costs one LDA and no repacking. Measured, not
;		assumed: COLOR 5,2 leaves $0376 = $25. GPC keeps no colour state of its own (CommandColor
;		emits PETSCII control codes and lets the KERNAL do the bookkeeping), so this really is
;		"the colour PRINT would have used", not a second, separate notion of colour.
;
;		The sentinel is 256, not 255, because $FF is a legal attribute (light grey on light grey).
;		OptionalColourCompile already pushes 256 for exactly that reason -- see the note on its
;		definition, and note that TILE gets this wrong and cannot write attribute $FF at all.
;
;		CHARACTERS ARE PETSCII, converted here. A screen code is not what a BASIC programmer has:
;		they have CHR$ and ASC, and no conversion exists anywhere else in GPC. One consequence is
;		worth knowing: pet2scr cannot reach screen codes $A0-$BF, the reverse-video glyphs, because
;		PETSCII expresses reverse with a control code rather than a character. That is not a loss
;		for a UI -- highlighting a menu row is a matter of swapping the ATTRIBUTE, which the colour
;		argument does directly.
;
;		NOTHING HERE CLIPS. x, y, w and h are bytes and are used as given, so a rectangle running
;		off the right edge wraps into the next row and one running off the bottom writes past the
;		end of the map. Zero width or height IS caught, because that is the one a program reaches
;		by accident (a computed size) and it would otherwise count down through 256 cells.
;
; ************************************************************************************************

;
;		Offsets into a border style's 8 bytes. This is VTUIlib's order, kept verbatim so the table
;		below is a checkable lift rather than a transcription: corners first as top-right,
;		top-left, bottom-right, bottom-left, then the four edges.
;
GPD_TR = 0
GPD_TL = 1
GPD_BR = 2
GPD_BL = 3
GPD_TOP = 4
GPD_BOTTOM = 5
GPD_LEFT = 6
GPD_RIGHT = 7

GPD_STYLES = 4

;
;		Style GPD_CUSTOM is the caller's own eight glyphs, and it is the entry immediately
;		AFTER the table -- so the drawing code below indexes it exactly as it indexes a
;		built-in one, and not a line of it changed. That adjacency is the whole trick: the
;		alternative was a second set of reads, or a pointer held in zero page across
;		TileSetAddress.
;
GPD_CUSTOM = 4

; ************************************************************************************************
;
;								GP.BOX x,y,w,h [,style] [,col]
;
; ************************************************************************************************

CommandGPBox: ;; [!gp.box]
		.entercmd
		phy
		ldx 	#5 							; every argument is numeric here
_CGBInteger:
		.floatinteger
		dex
		bpl 	_CGBInteger 				; leaves X = $FF, so X is free scratch from here on
		;
		jsr 	GPDrawGeometry
		beq 	_CGBExit
		lda 	gpdW 						; a box needs two columns and two rows to have two
		cmp 	#2 							; corners; anything less has no drawing to do that
		bcc 	_CGBExit 					; would not be a lie about what was asked for
		lda 	gpdH
		cmp 	#2
		bcc 	_CGBExit
		;
		ldx 	#5
		jsr 	GPDrawColour
		;
		lda 	NSMantissa1+4 				; A STYLE OF 256 OR MORE IS AN ADDRESS, not a style
		bne 	_CGBCustom 					; -- there are only four, so the high byte is free
		lda 	NSMantissa0+4 				; the style, as an offset into the glyph table
		cmp 	#GPD_STYLES
		bcs 	_CGBBadStyle
_CGBIndex:
		asl 	a
		asl 	a
		asl 	a
		tax 								; and X holds it for the whole of the drawing below,
		 									; because TileSetAddress leaves X alone
		;
		jsr 	GPDrawAddress 				; the top row: corner, edge run, corner
		lda 	GPDrawBorder+GPD_TL,x
		jsr 	GPDrawPutCell
		lda 	GPDrawBorder+GPD_TOP,x
		jsr 	GPDrawRun
		lda 	GPDrawBorder+GPD_TR,x
		jsr 	GPDrawPutCell
		;
		lda 	gpdH 						; the sides: two cells a row, so they are addressed
		sec 								; individually rather than walked
		sbc 	#2
		sta 	gpdCount
		beq 	_CGBBottom
_CGBSide:
		inc 	gpdY
		jsr 	GPDrawAddress
		lda 	GPDrawBorder+GPD_LEFT,x
		jsr 	GPDrawPutCell
		lda 	gpdX
		clc
		adc 	gpdW
		dec 	a 							; x + w - 1, the far column
		jsr 	GPDrawAddressA
		lda 	GPDrawBorder+GPD_RIGHT,x
		jsr 	GPDrawPutCell
		dec 	gpdCount
		bne 	_CGBSide
_CGBBottom:
		inc 	gpdY
		jsr 	GPDrawAddress
		lda 	GPDrawBorder+GPD_BL,x
		jsr 	GPDrawPutCell
		lda 	GPDrawBorder+GPD_BOTTOM,x
		jsr 	GPDrawRun
		lda 	GPDrawBorder+GPD_BR,x
		jsr 	GPDrawPutCell
_CGBExit:
		ply
		ldx 	#$FF
		.exitcmd

_CGBBadStyle:
		ply
		.error_range

;
;		The caller's eight glyphs, copied into the entry past the table and then drawn as if
;		they had always been there. zTemp0 is free at this point -- GPDrawGeometry and
;		GPDrawColour are done with it, and nothing that uses it is called until GPDrawAddress
;		below, by which time this is finished.
;
;		THE BYTES ARE SCREEN CODES, in the table's own order, and NOT PETSCII: the table is
;		read straight to the cell with no pet2scr, so a custom set has to match it. GP.FILL
;		converts and this does not, which is a real difference and is documented in
;		GPB.INC.BL where a caller will meet it.
;
_CGBCustom:
		sta 	zTemp0+1
		lda 	NSMantissa0+4
		sta 	zTemp0
		ldy 	#7
_CGBCustomCopy:
		lda 	(zTemp0),y
		sta 	GPDrawCustom,y
		dey
		bpl 	_CGBCustomCopy
		lda 	#GPD_CUSTOM
		bra 	_CGBIndex

; ************************************************************************************************
;
;								GP.FILL x,y,w,h,char [,col]
;
; ************************************************************************************************

CommandGPFill: ;; [!gp.fill]
		.entercmd
		phy
		ldx 	#5
_CGFInteger:
		.floatinteger
		dex
		bpl 	_CGFInteger
		;
		jsr 	GPDrawGeometry
		beq 	_CGFExit
		ldx 	#5
		jsr 	GPDrawColour
		lda 	NSMantissa0+4 				; the character is converted ONCE, not per cell
		bit 	X16_EditorMode 				; bit 6 -> V. BIT leaves A alone, which is the point:
		bvs 	_CGFRaw 					; in ISO mode the byte already IS the tile index
		jsr 	GPDrawPet2Scr
_CGFRaw:
		sta 	gpdChar
_CGFRow:
		jsr 	GPDrawAddress 				; one address per row; the increment does the rest
		ldy 	gpdW
		lda 	gpdChar 					; GPDrawPutCell hands A back, so it is loaded once
_CGFCell:
		jsr 	GPDrawPutCell
		dey
		bne 	_CGFCell
		inc 	gpdY
		dec 	gpdH
		bne 	_CGFRow
_CGFExit:
		ply
		ldx 	#$FF
		.exitcmd

; ************************************************************************************************
;
;								GP.PRINTAT x,y,text$ [,col]
;
;		IT FOLLOWS THE SCREEN INTO ISO MODE, per character, for five bytes and no keyword.
;
;		In ISO mode (PRINT CHR$(15), or the user pressing Ctrl+O) the VERA tile index IS the
;		character code, so translating PETSCII to a screen code is not merely wasted work, it is
;		WRONG: 'A' would go in as $01 and the string would come out as garbage. That made every
;		drawn interface -- LINEINPUT's fields, MENUVERT's bars -- unusable in ISO mode, which is
;		exactly the mode a program wants when it needs both letter cases.
;
;		BIT X16_EditorMode puts the KERNAL's own ISO bit into V and leaves A, X and Y untouched,
;		so the test costs 4 cycles and no register in the middle of a character loop. Asking the
;		KERNAL rather than being told means there is nothing to declare and nothing to get wrong:
;		no keyword, no argument threaded through every caller, no mode variable to leave stale.
;		Every existing program that switches charset is simply correct now, unchanged.
;
;		The bill is +7 cycles a cell in PETSCII mode, 94 -> 101, against 41 SAVED in ISO mode
;		(94 -> 60) because the whole GPDrawPet2Scr call goes away. Hoisting the test above the
;		loop would buy back the 7 for about eight more bytes of a block with 36 free; it is not
;		worth it at seven cycles on a command that draws chrome, not inner loops.
;
;		GP.FILL MAKES THE SAME TEST, and it is cheaper there: its ONE character is converted
;		before the loop, so the test goes beside that single jsr and costs nothing per cell.
;		The old excuse was that $20 is a fixed point of the offset table ($20>>5 = 1, offset
;		$00), so a space fill -- padding and blanking, all the library itself does -- was right
;		either way. That held until GUI.FRAME filled non-space glyphs, and the editor had to
;		park its six frame tiles at $C0-$C5 and ask for them 64 lower to cancel a conversion
;		nobody wanted. An undocumented bias that cost a day to find is not worth five bytes.
;
; ************************************************************************************************

CommandGPPrintAt: ;; [!gp.printat]
		.entercmd
		phy
		ldx 	#1 							; x and y. Slot 2 is the STRING and must not be run
_CGPInteger: 								; through FloatIntegerPart at all
		.floatinteger
		dex
		bpl 	_CGPInteger
		ldx 	#3
		.floatinteger 						; the optional colour, past the string
		;
		lda 	NSMantissa0+0
		sta 	gpdX
		lda 	NSMantissa0+1
		sta 	gpdY
		ldx 	#3
		jsr 	GPDrawColour
		;
		lda 	NSMantissa0+2 				; the stack carries the address of [length][data]
		sta 	zTemp0
		lda 	NSMantissa1+2
		sta 	zTemp0+1
		lda 	(zTemp0)
		beq 	_CGPExit 					; an empty string draws nothing
		sta 	gpdCount
		;
		jsr 	GPDrawAddress 				; addressed once for the whole string
_CGPChar:
		inc 	zTemp0 						; pre-bumped, so the length byte is stepped over
		bne 	_CGPNoCarry
		inc 	zTemp0+1
_CGPNoCarry:
		lda 	(zTemp0)
		bit 	X16_EditorMode 				; bit 6 -> V. BIT leaves A alone, which is the point:
		bvs 	_CGPRaw 					; in ISO mode the byte already IS the tile index
		jsr 	GPDrawPet2Scr
_CGPRaw:
		jsr 	GPDrawPutCell
		dec 	gpdCount
		bne 	_CGPChar
_CGPExit:
		ply
		ldx 	#$FF
		.exitcmd

; ************************************************************************************************
;
;		x, y, w and h out of stack slots 0..3. Returns Z SET when there is nothing to draw --
;		either dimension zero -- which every caller tests, because a zero count would otherwise
;		count down through 256 cells and scribble over a whole screen.
;
; ************************************************************************************************

GPDrawGeometry:
		lda 	NSMantissa0+0
		sta 	gpdX
		lda 	NSMantissa0+1
		sta 	gpdY
		lda 	NSMantissa0+2
		sta 	gpdW
		lda 	NSMantissa0+3
		sta 	gpdH
		beq 	_GDGNone 					; h = 0, and Z is already set
		lda 	gpdW 						; otherwise the answer is whether w is zero
_GDGNone:
		rts

; ************************************************************************************************
;
;		The optional colour, out of the stack slot named by X. A non-zero HIGH byte is the 256
;		that OptionalColourCompile pushes for "omitted", which no real attribute can produce.
;
; ************************************************************************************************

GPDrawColour:
		lda 	NSMantissa1,x
		beq 	_GDCGiven
		lda 	X16_TextColour 				; what COLOR last set, already in attribute packing
		sta 	gpdCol
		rts
_GDCGiven:
		lda 	NSMantissa0,x
		sta 	gpdCol
		rts

; ************************************************************************************************
;
;		Point VERA at column A (GPDrawAddressA) or at gpdX (GPDrawAddress) of row gpdY, with the
;		auto-increment set so that consecutive accesses walk character, attribute, character...
;		TileSetAddress is the primitive TILE uses; it derives the map base and the row stride from
;		VERA rather than assuming them, and it does not touch X.
;
; ************************************************************************************************

GPDrawAddress:
		lda 	gpdX
GPDrawAddressA:
		sta 	tileX
		stz 	tileX+1
		lda 	gpdY
		sta 	tileY
		stz 	tileY+1
		jmp 	TileSetAddress

; ************************************************************************************************
;
;		Write the screen code in A and the current colour at the VERA address, and step on to the
;		next cell. A is preserved, so a caller can repeat one glyph without reloading it.
;
; ************************************************************************************************

GPDrawPutCell:
		sta 	VRAMData0
		pha
		lda 	gpdCol
		sta 	VRAMData0
		pla
		rts

;
;		The glyph in A, w-2 times: the run BETWEEN two corners. Only called after the w >= 2
;		check, so the double decrement cannot underflow.
;
GPDrawRun:
		ldy 	gpdW
		dey
		dey
		beq 	_GDRDone 					; w = 2 is two corners and no edge at all
_GDRLoop:
		jsr 	GPDrawPutCell
		dey
		bne 	_GDRLoop
_GDRDone:
		rts

; ************************************************************************************************
;
;		PETSCII in A to a screen code in A. Y is used; X is not.
;
;		The whole conversion is one add from a table indexed by the top three bits, which is how
;		prog8 does it and is far smaller than the chain of compares it replaces. $FF is the one
;		value the table cannot express -- pi is screen code $5E, and the arithmetic gives $7F --
;		so it is tested for. CHR$(222) is the same character and needs no special case.
;
; ************************************************************************************************

GPDrawPet2Scr:
		cmp 	#$FF
		beq 	_GP2SPi
		pha
		lsr 	a
		lsr 	a
		lsr 	a
		lsr 	a
		lsr 	a
		tay
		pla
		clc
		adc 	GPDrawP2SOffset,y
		rts
_GP2SPi:
		lda 	#$5E
		rts

;
;		Added, not subtracted: every entry is the 8-bit offset from the PETSCII range to the
;		screen code range, so $C0 here means "minus $40".
;
GPDrawP2SOffset:
		.byte 	$80,$00,$C0,$E0,$40,$C0,$80,$80

; ************************************************************************************************
;
;		The four border styles, eight SCREEN CODES each, lifted byte for byte from VTUIlib (public
;		domain). Order per GPD_* above: TR, TL, BR, BL, top, bottom, left, right.
;
;		Verified against the ROM charset rather than taken on trust -- rendering the bitmaps out
;		of rom.bin is what settled the slot order, e.g. style 3's $77 is two filled rows at the
;		TOP of the cell and its $74 two filled columns at the LEFT, which no other reading fits.
;
; ************************************************************************************************

GPDrawBorder:
		.byte 	$A0,$A0,$A0,$A0,$A0,$A0,$A0,$A0 	; 0  solid block
		.byte 	$6E,$70,$7D,$6D,$40,$40,$42,$42 	; 1  single line
		.byte 	$49,$55,$4B,$4A,$40,$40,$42,$42 	; 2  single line, rounded corners
		.byte 	$50,$4F,$7A,$4C,$77,$6F,$74,$6A 	; 3  thick line
;
;		Style 4: the CALLER'S eight, copied in by _CGBCustom. It must stay immediately after
;		the table -- that is what lets style 4 be indexed like any other.
;
GPDrawCustom:
		.fill 	8

		.send 	code

		.section storage
gpdX:
		.fill 	1
gpdY: 										; counts UP as the rows are drawn
		.fill 	1
gpdW:
		.fill 	1
gpdH: 										; counts DOWN as the rows are drawn
		.fill 	1
gpdChar: 									; GP.FILL's glyph, already a screen code
		.fill 	1
gpdCol: 									; the attribute written beside every character
		.fill 	1
gpdCount: 									; side rows for GP.BOX, characters for GP.PRINTAT
		.fill 	1
		.send 	storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;		17/08/26		Written.
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		gpfncall.asm
;		Purpose:	.fnsave / .fnrestore / .fnpush / .fnpop -- the frame stack under a call
;		Created:	8th September 2026
;		Author : 	Steven De George SR
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;								.fnsave  /  .fnrestore
;
;		GP.SUB needs neither of these and GP.FN cannot work without them. A GP.SUB is a
;		STATEMENT: its arguments are stored into the formals before the call, so nothing of the
;		caller's is half-finished when the routine runs. GP.FN is an EXPRESSION TERM, and
;		"A + GP.FN(V,1)" reaches the call with A already pushed.
;
;		WHAT DESTROYS IT IS new.line, AND EVERY SOURCE LINE HAS ONE. CommandNewLine is four
;		instructions -- stz stringInitialised and ldx #$FF -- and the compiler emits it in front
;		of every line, so the callee wipes the caller's evaluation stack and hands its string
;		temporaries out again on its FIRST line. DEF FN escapes this only because its body is
;		compiled inline on the DEF line and so contains no new.line at all; a GP.DEFPROC body is
;		ordinary source lines and cannot.
;
;		SO THE CALL SITE BRACKETS THE .fngosub WITH THESE TWO. The compiler emits
;
;			<argument> ... into the formals, exactly as GP.SUB does
;			.fnsave
;			.fngosub  <body>
;			.fnrestore
;			<read the RETURNS variable>
;
;		and the result comes back in a VARIABLE rather than on the stack, which is what RETURNS
;		names. It has to: the body is many lines, and the stack does not survive them.
;
;		ONE FRAME PER SLOT, NOT ONE FRAME FOR THE LOT. A frame's size lives in the low five bits
;		of its marker, so 31 bytes is the most one can hold, and twelve slots of six bytes is 72.
;		A frame apiece keeps every marker honest, which is what lets StackFindFrame walk over
;		them correctly if it ever has to. They are pushed TOP DOWN so .fnrestore, which pops from
;		the top, meets slot 0 first and can rebuild X by counting.
;
;		AND THE STRING HALF IS A BASE, NOT A COPY. Temporaries start stringTempPages below the
;		heap ceiling; raising it for the length of the call puts the callee's own resets BELOW
;		the temporaries the caller is still holding, so nothing has to be copied anywhere. The
;		heap ceiling itself could not be moved instead -- StringConcrete's scavenger walks the
;		blocks upward from it and needs them to tile it exactly.
;
;		All four handlers are above GPBase, so they cost a program with no GP block nothing but
;		the vector slots -- four bytes apiece -- that every system token costs.
;
; ************************************************************************************************

CommandXFnSave: ;; [.fnsave]
		.entercmd 							; X is the caller's live stack index
		phy 								; ...and Y is the code offset, which the frame
		phx 								; writes below need for themselves
		;
		;		Make the string state definite before saving it: the caller may not have
		;		allocated a temporary yet, and then stringTempPointer is stale rather than wrong.
		;
		jsr 	StringInitialise
		;
		lda 	#FRAME_FNSTATE
		jsr 	StackOpenFrame
		ldy 	#1
		lda 	stringTempPointer
		sta 	(runtimeStackPtr),y
		iny
		lda 	stringTempPointer+1
		sta 	(runtimeStackPtr),y
		iny
		lda 	stringTempPages
		sta 	(runtimeStackPtr),y
		;
		;		Then the live slots, highest first.
		;
		pla
		sta 	fnSaveIndex
_CXSLoop:
		ldx 	fnSaveIndex
		bmi 	_CXSBase 					; $FF is an empty stack, and the usual case
		jsr 	FnPushSlot
		dec 	fnSaveIndex
		bra 	_CXSLoop
		;
		;		Drop the temporary base below what the caller is holding, and a page clear of it.
		;		It only ever goes down here -- a nested call has already taken it further, and
		;		its own .fnrestore is what brings it back.
		;
_CXSBase:
		sec
		lda 	stringHighMemory+1
		sbc 	stringTempPointer+1
		inc 	a
		cmp 	stringTempPages
		bcc 	_CXSDone
		sta 	stringTempPages
		;
		;		...and stop if that has taken the temporaries into the arrays. Nothing downstream
		;		would notice: StringInitialise tests the heap CEILING against availableMemory, and
		;		the ceiling has not moved.
		;
		sec
		lda 	stringHighMemory+1
		sbc 	stringTempPages
		cmp 	availableMemory+1
		bcc 	_CXSMemory
_CXSDone:
		stz 	stringInitialised 			; so the callee allocates from the new base
		ldx 	#$FF 						; the saved slots are the caller's copy now, and the
											; callee is entitled to the whole stack
		ply
		.exitcmd

_CXSMemory:
		.error_memory

; ************************************************************************************************
;
;		Put both back. The slot frames rebuild X by counting, so the caller's depth is not
;		stored anywhere -- an empty stack simply has no slot frames and leaves X at $FF.
;
; ************************************************************************************************

CommandXFnRestore: ;; [.fnrestore]
		.entercmd
		phy
		ldx 	#$FF
_CXRLoop:
		lda 	(runtimeStackPtr) 			; frame marker on top
		and 	#$E0 						; the id is the upper 3 bits (frames.inc)
		cmp 	#FRAME_FNSLOT & $E0
		bne 	_CXRState
		inx
		cpx 	#MathStackSize 				; more slot frames than the stack has slots, so a store
		bcs 	_CXRBroken 					; here would run off NSExponent into whatever is next
		jsr 	FnPullSlot
		bra 	_CXRLoop
_CXRState:
		cmp 	#FRAME_FNSTATE & $E0 		; whatever else it is, the pairing is broken
		bne 	_CXRBroken
		ldy 	#1
		lda 	(runtimeStackPtr),y
		sta 	stringTempPointer
		iny
		lda 	(runtimeStackPtr),y
		sta 	stringTempPointer+1
		iny
		lda 	(runtimeStackPtr),y
		sta 	stringTempPages
		jsr 	StackCloseFrame
		lda 	#$FF 						; the caller's temporaries are live again, so nothing
		sta 	stringInitialised 			; may hand that memory out a second time
		ply
		.exitcmd

_CXRBroken:
		.error_structure

; ************************************************************************************************
;
;								.fnpush  /  .fnpop
;
;		AN ARGUMENT LIST IS EVALUATED IN FULL BEFORE ANY OF IT IS STORED, and these are where
;		it waits. A formal is a plain variable, so a call that stored as it read would let
;		GP.FN(AREA,2,GP.FN(AREA,3,4)) write A.W for the inner call while the outer call's 2 was
;		still sitting in it -- the wrong answer, silently, with both passes agreeing.
;
;		THE EVALUATION STACK IS THE WRONG PLACE TO HOLD THEM. It is MathStackSize -- twelve --
;		slots for the whole expression, it has no overflow check anywhere, and slot 12 is
;		NSMantissa0[0]: overflowing it corrupts the bottom of the same stack rather than
;		reporting anything. Twelve formals against twelve slots put a real program one deep
;		argument away from that, and holding the arguments there would have made the formal
;		count a cap on what may be written.
;
;		SO EACH ARGUMENT GOES TO THE FRAME STACK AS IT IS EVALUATED, and comes back one at a
;		time as the stores run. The evaluation stack then holds ONE argument at a time however
;		many there are, the depth a call needs is the depth of its deepest single argument, and
;		the frame stack -- 4K, and checked by StackOpenFrame -- is what a long list runs into.
;
;		THE LAST ARGUMENT IS NEVER PUSHED. It is evaluated last and stored first, so nothing
;		runs between the two and there is nothing to protect it from. A verb of one formal
;		therefore emits neither of these and costs exactly what the longhand did.
;
;		They use FRAME_FNSLOT, the same frame .fnsave pushes, because that is what they are:
;		one saved evaluation stack slot. The two never meet -- .fnsave's frames sit above its
;		FRAME_FNSTATE and .fnrestore stops there -- and .fnpop pops exactly one frame rather
;		than counting, so an argument frame left under a callee's own frames is invisible to it.
;
; ************************************************************************************************

CommandXFnPush: ;; [.fnpush]
		.entercmd 							; X is the argument just evaluated
		phy
		jsr 	FnPushSlot
		dex 								; it lives on the frame stack now, so the slot is free
		ply
		.exitcmd

CommandXFnPop: ;; [.fnpop]
		.entercmd
		phy
		lda 	(runtimeStackPtr) 			; frame marker on top
		and 	#$E0
		cmp 	#FRAME_FNSLOT & $E0 		; anything else and the pairing is broken
		bne 	_CXPBroken
		inx
		cpx 	#MathStackSize 				; and a store here would run off NSExponent
		bcs 	_CXPBroken
		jsr 	FnPullSlot
		ply
		.exitcmd

_CXPBroken:
		.error_structure

; ************************************************************************************************
;
;		One evaluation stack slot to a new frame, and one back from the top frame. X is the slot
;		in both and both leave it alone -- StackOpenFrame and StackCloseFrame never touch X, and
;		the restore loop above has always counted on the second of those.
;
; ************************************************************************************************

FnPushSlot:
		lda 	#FRAME_FNSLOT
		jsr 	StackOpenFrame
		ldy 	#1
		lda 	NSStatus,x
		sta 	(runtimeStackPtr),y
		iny
		lda 	NSMantissa0,x
		sta 	(runtimeStackPtr),y
		iny
		lda 	NSMantissa1,x
		sta 	(runtimeStackPtr),y
		iny
		lda 	NSMantissa2,x
		sta 	(runtimeStackPtr),y
		iny
		lda 	NSMantissa3,x
		sta 	(runtimeStackPtr),y
		iny
		lda 	NSExponent,x
		sta 	(runtimeStackPtr),y
		rts

FnPullSlot:
		ldy 	#1
		lda 	(runtimeStackPtr),y
		sta 	NSStatus,x
		iny
		lda 	(runtimeStackPtr),y
		sta 	NSMantissa0,x
		iny
		lda 	(runtimeStackPtr),y
		sta 	NSMantissa1,x
		iny
		lda 	(runtimeStackPtr),y
		sta 	NSMantissa2,x
		iny
		lda 	(runtimeStackPtr),y
		sta 	NSMantissa3,x
		iny
		lda 	(runtimeStackPtr),y
		sta 	NSExponent,x
		jmp 	StackCloseFrame

		.send 	code

; ************************************************************************************************
;
;		The slot being saved. In the storage section, which lives in the $0400-$0801 hole BELOW
;		the object's load address, so it is uninitialised RAM at run time and not a byte in the
;		file.
;
; ************************************************************************************************

		.section storage
fnSaveIndex:
		.fill 	1
		.send 	storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;		08/09/26		Written.
;		08/09/26		.fnpush / .fnpop added: an argument list waits on the frame stack, not on
;						the twelve-slot evaluation stack it used to fill one slot a formal.
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		gpstring.asm
;		Purpose:	GP.FIND and GP.STRPTR
;		Created:	16th August 2026
;		Reviewed: 	No
;		Author : 	Steven De George SR
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;		Both of these rest on one fact, verified in memory/read_string.asm: ReadStringZTemp0Sub
;		reads a string variable's block address and ADDS 2 before pushing it. So a string on the
;		number stack is already the address of [ActLen][Data] -- length at the address itself,
;		first character at address+1, and the block's capacity two bytes BELOW:
;
;			PEEK(A-2) = MaxLen (capacity)      PEEK(A) = current length
;			PEEK(A-1) = control byte           A+1     = first character
;
; ************************************************************************************************

; ************************************************************************************************
;
;						GP.INSTR(haystack$, needle$ [,start]) -> position, 0 if absent
;
;		The gap this fills: GPC has no string search of any kind -- no INSTR, nothing. Done in
;		BASIC it is a MID$ loop, which allocates a temporary string per character compared.
;
;		START is optional and 0 means "from the beginning", so it shares OptionalZeroCompile with
;		GP.CALL's registers -- no sentinel needed, because 0 is not a legal 1-based position and
;		means the same thing as 1 anyway.
;
;		X is the number stack pointer and cannot be borrowed, so the outer index lives in memory
;		and Y does the inner compare, counting DOWN from the needle length -- which also makes the
;		mismatch exit the common case's fastest path.
;
; ************************************************************************************************

UnaryGPInstr: ;; [gp.instr]
		.entercmd
		phy 								; Y is the code pointer offset
		;
		jsr 	FloatIntegerPart 			; <start>, the last argument pushed
		lda 	NSMantissa0,x
		bne 	_GIHaveStart
		lda 	#1 							; 0 (or omitted) means from the beginning
_GIHaveStart:
		sta 	gpsIndex 					; 1-based for the moment
		dex
		;
		lda 	NSMantissa0,x 				; <needle>
		sta 	zTemp1
		lda 	NSMantissa1,x
		sta 	zTemp1+1
		dex 								; X now addresses <haystack>, where the result goes
		;
		lda 	NSMantissa0,x 				; <haystack> becomes the sliding compare pointer
		sta 	zTemp2
		lda 	NSMantissa1,x
		sta 	zTemp2+1
		;
		lda 	(zTemp2) 					; lengths
		sta 	gpsHayLen
		lda 	(zTemp1)
		sta 	gpsNeedLen
		beq 	_GINotFound 				; an empty needle never matches
		;
		dec 	gpsIndex 					; 0-based from here, and slide the pointer to it
		clc
		lda 	zTemp2
		adc 	gpsIndex
		sta 	zTemp2
		bcc 	_GIOuter
		inc 	zTemp2+1
		;
		;		Does the needle still fit in what is left? Carry out means the sum passed 255,
		;		which cannot fit either.
		;
_GIOuter:
		clc
		lda 	gpsIndex
		adc 	gpsNeedLen
		bcs 	_GINotFound
		cmp 	gpsHayLen
		beq 	_GITry 						; an exact fit is still a fit
		bcs 	_GINotFound
_GITry:
		ldy 	gpsNeedLen 					; compare backwards, 1 is the first data byte
_GIInner:
		lda 	(zTemp1),y
		cmp 	(zTemp2),y
		bne 	_GIAdvance
		dey
		bne 	_GIInner
		;
		inc 	gpsIndex 					; matched -- report it 1-based
		lda 	gpsIndex
		bra 	_GIResult

_GIAdvance:
		inc 	gpsIndex
		inc 	zTemp2
		bne 	_GIOuter
		inc 	zTemp2+1
		bra 	_GIOuter

_GINotFound:
		lda 	#0
_GIResult:
		ply
		jsr 	FloatSetByte 				; X already addresses the result slot
		.exitcmd

; ************************************************************************************************
;
;					GP.INSTRREV(haystack$, needle$ [,start]) -> position, 0 if absent
;
;		*** NOT BUILT. *** This block is a design note, not documentation of shipped code: there is
;		no handler below it, no vector marker, and no token in getGP(). It is written in the
;		present tense like the entries either side of it, which is exactly how it would come to be
;		mistaken for a keyword that exists -- so it says so here. Everything below is what it WOULD
;		do if built.
;
;		(And the marker is described in words rather than shown, for the reason spelled out in the
;		GP.COMP block below: pcode.py scans comments too, and a literal one here fails the build.)
;
;		The LAST occurrence rather than the first: the extension in a filename, the last space to
;		break a line at. Named and shaped after FreeBASIC's INSTRREV (VB spells it InStrRev), which
;		is a separate function rather than PowerBASIC's negative-start-on-INSTR, because
;		GP.INSTR(f$,".",-1) does not read as "find the last one" to anyone who has not used
;		PowerBASIC specifically.
;
;		START is where a match may START, and caps the search from above; 0 or omitted means from
;		the end, which is FreeBASIC's -1 default written in this table's usual way.
;
;		It shares the inner compare with GP.INSTR and differs only in the outer walk, which runs
;		DOWNWARD from the last index a match could possibly start at. That last index is computed
;		once, which is why -- unlike the forward scan -- there is no "does it still fit" test in
;		the loop: everything at or below it fits by construction.
;
;		SHIFTED. It walks a whole string, so the 17 extra cycles of a shifted dispatch amortise,
;		and searching backwards is the rarer direction. GP.INSTR keeps the unshifted slot.
;
; ************************************************************************************************
;
;					GP.COMP(a$, b$) -> -1, 0 or 1, comparing WITHOUT case
;
;		-1 if a$ sorts before b$, 0 if they match, 1 if a$ sorts after. Same shape as prog8's
;		compare_nocase and as strcmp everywhere else, and -1/0/1 is the natural set in BASIC
;		rather than the 255 the internal comparator hands back, because BASIC's own TRUE is -1.
;		SGN builds its result the same way: FloatSetByte, then stamp the sign into NSStatus.
;
;		This is a copy of CompareStrings (strings/compare.asm, the s.cmp opcode behind = < >) with
;		two changes: both characters are folded to upper case before the compare, and the result
;		is signed. Not shared with it -- the fold is in the inner loop, so hoisting it into
;		compare.asm would put a test on the hot path of every string comparison in every program
;		to save about forty bytes here.
;
;		(Do not write a marker in square brackets after a double semicolon in a comment, even in
;		prose: common-scripts/pcode.py scans for exactly that and will read it as a real opcode
;		declaration. It fails the build with "Bad line", which is how this note came to exist.)
;
;		LENGTH still breaks a tie, unfolded, and case never enters into that: "abc" vs "ABCD"
;		compares equal for three characters and then the shorter one sorts first.
;
;		SHIFTED. It walks a whole string, like the trims.
;
; ************************************************************************************************

UnaryGPComp: ;; [!gp.comp]
		.entercmd
		dex
		;
		lda 	NSMantissa0,x 				; a$ -> zTemp0
		sta 	zTemp0
		lda 	NSMantissa1,x
		sta 	zTemp0+1
		lda 	NSMantissa0+1,x 			; b$ -> zTemp1
		sta 	zTemp1
		lda 	NSMantissa1+1,x
		sta 	zTemp1+1
		;
		phx 								; X is the number stack pointer, and the count below
		phy 								; needs a register -- so borrow it and put it back
		;
		lda 	(zTemp0) 					; compare min(len(a$),len(b$)) characters
		cmp 	(zTemp1)
		bcc 	_GCShorter
		lda 	(zTemp1)
_GCShorter:
		tax
		beq 	_GCEqualSoFar 				; one of them is empty, so length decides
		ldy 	#0
_GCLoop:
		iny
		lda 	(zTemp1),y 					; fold b$'s character into scratch first, so that A
		jsr 	GPFoldUpper 				; still holds a$'s when the compare happens and the
		sta 	gpsNeedLen 					; carry means what it does in CompareStrings
		lda 	(zTemp0),y
		jsr 	GPFoldUpper
		cmp 	gpsNeedLen
		bne 	_GCDiffer
		dex
		bne 	_GCLoop
_GCEqualSoFar:
		sec 								; every common character matched, so the shorter
		lda 	(zTemp0) 					; string sorts first -- lengths decide, unfolded
		sbc 	(zTemp1)
		beq 	_GCSame
_GCDiffer:
		bcs 	_GCAfter
		;
		ply 								; a$ sorts BEFORE b$
		plx
		lda 	#1
		jsr 	FloatSetByte
		lda 	NSStatus,x 					; ... made negative, exactly as SGN does it
		ora 	#$80
		sta 	NSStatus,x
		.exitcmd
_GCAfter:
		ply 								; a$ sorts AFTER b$
		plx
		lda 	#1
		jsr 	FloatSetByte
		.exitcmd
_GCSame:
		ply
		plx
		lda 	#0
		jsr 	FloatSetByte
		.exitcmd

;
;		A -> upper case if it is a lower case letter, untouched otherwise. Clobbers A only, so
;		PETSCII graphics, digits and punctuation all pass straight through.
;
GPFoldUpper:
		cmp 	#'a'
		bcc 	_GFUOut
		cmp 	#'z'+1
		bcs 	_GFUOut
		and 	#$DF
_GFUOut:
		rts

; ************************************************************************************************
;
;								GP.STRPTR(a$) -> address of [ActLen][Data]
;
;		The address is ALREADY what the number stack carries, so this is a retype and nothing
;		else: clear the string bit and the unused mantissa bytes and the same value is a number.
;
;		Deliberately NOT X16's STRPTR shape (which returns the first character). GPC rejects that
;		one outright -- X:UnsupportedCompile -- because the CBM [len,lo,hi] descriptor does not
;		describe GPC's blocks. Exposing GPC's own layout is safe where exposing the ROM's was not,
;		and length-then-characters is a one line rule to learn.
;
;		CAVEAT: a string LITERAL is pushed by CommandPushS pointing into the p-code itself, so an
;		address from GP.STRPTR on a literal is read-only. Writing through it modifies the program.
;
; ************************************************************************************************

UnaryGPStrPtr: ;; [gp.strptr]
		.entercmd
		stz 	NSMantissa2,x 				; the address is already in mantissa 0/1
		stz 	NSMantissa3,x
		stz 	NSExponent,x
		stz 	NSStatus,x 					; NSSIFloat is $00 -- string bit cleared, now a number
		.exitcmd
; ************************************************************************************************
;
;		GP.UPPER / GP.LOWER / GP.TRIM / GP.LTRIM / GP.RTRIM WERE HERE, and are
;		GPC-BASIC/STRCASE.INC.BL now -- written in GP.ASM, one blob with a mode byte tested once
;		at entry. So was their shared GPStringAddress. 188 bytes, removed 1st September 2026.
;
;		The reason is the block, not the code: it is ALL OR NOTHING -- every byte written into
;		the object AND taken off the bottom of the workspace, for any program that uses one GP
;		keyword -- and outside their own example file these five had exactly ONE caller in the
;		whole tree. ObjectBase $3d00 -> $3c00, which is 512 bytes back for every GP program.
;
;		GP.STRPTR STAYED, and is now load-bearing rather than a curiosity: a BASL subroutine
;		cannot be passed a variable, so the module takes the block ADDRESS and rewrites it where
;		it lies. Copying the caller's string in and out instead would be two allocations and two
;		copies per call, which is the exact heap traffic these were assembly to avoid.
;
;		WHAT THE MOVE GIVES UP: StringVariableCompile enforced a string VARIABLE at the call
;		site, so a literal could never reach a handler. A GOSUB has no equivalent, and
;		GP.STRPTR("text") is the address of the literal inside the p-code -- upper-casing that
;		edits the program. The module's header says so; the compiler can no longer say it.
;
;		WHY THERE WAS NO GP.PAD AMONG THEM. It was written, it worked, and it was removed on
;		16/08/26. These five all SHRINK or rewrite a string in place, which needs nothing but the
;		block. Padding GROWS one -- and a handler only ever receives the block address, never the
;		variable slot, so it cannot repoint the variable at a bigger block. That capped GP.PAD at
;		the capacity the string was born with (StringConcrete: length+50%, min 10), so padding
;		"HI" to a 20 column field -- the entire point of the command -- raised OUT OF RANGE.
;		Padding is STR.PAD in GPC-BASIC/STRINGS.INC.BL, one line of BASL built on RPT$,
;		where an ordinary assignment reallocates for free.
;
; ************************************************************************************************

		.send 	code

		.section storage
gpsHayLen:									; the string being searched
		.fill 	1
gpsNeedLen: 								; what is being looked for
		.fill 	1
gpsIndex: 									; how far into the haystack the compare has reached
		.fill 	1
		.send 	storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;		16/08/26		Written.
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		unwind.asm
;		Purpose:	.unwind <n> -- close n block frames so a GOTO can leave GP.DO / GP.SELECT
;		Created:	31st August 2026
;		Author : 	Steven De George SR
;
; ************************************************************************************************
; ************************************************************************************************

		.section 	code

; ************************************************************************************************
;
;								.unwind <count>
;
;		GP.ENDSEL and GP.LOOP are what release a block's stack frame, so a GOTO that jumps past
;		them leaks one -- and in a loop that is one per pass. A GP.SELECT frame is 7 bytes against
;		a 4K frame stack, so a leaking select in a key loop dies after about 585 keystrokes.
;
;		This closes the innermost <count> BLOCK frames, and the compiler is what works out the
;		count: FixBranches knows the block depth at the GOTO and at its target, and the difference
;		is how many blocks the jump leaves. A count of zero is the normal case and does nothing --
;		the whole opcode is then two p-code bytes and about a dozen cycles.
;
;		STRAYS ARE DISCARDED WITHOUT BEING COUNTED. A FOR abandoned inside a case body sits above
;		the select's frame, and it has to go too, but it is not one of the blocks being left. This
;		is the same rule StackFindFrame applies -- it throws everything above the frame it wants --
;		written out here because we are counting rather than searching for a type.
;
;		AND IT STOPS AT $FF. That is the stack-empty marker, and reaching it means the count was
;		wrong; closing "frames" past it would walk off the end of the frame stack and into the
;		workspace. Stopping is silent on purpose: FixBranches has already raised BLOCK MISMATCH
;		for the structural errors it can see, and there is nothing useful to report from here.
;
;		ONLY GP.DO OPENS A BLOCK FRAME NOW. GP.SELECT did until 1st September 2026, when its
;		selector was restricted to a plain variable and the frame that kept an expression alive
;		became unnecessary -- so a GOTO leaving a select has nothing to close, and neither the
;		compiler nor FixBranches counts one any more. The two lines that recognised a select
;		frame here went with it.
;
;		WHY A SEPARATE OPCODE RATHER THAN gp.loop. gp.loop does the right thing to a loop frame
;		and emitting one before the GOTO would have cost nothing -- but FixBranches counts loop
;		nesting on gp.do/gp.loop, so an extra one inside a loop body captures that body's own
;		structure and sends its branches to the wrong place. The unwind has to be a token the
;		scanners do not count. It costs one vector slot, two bytes, in every compiled program;
;		the handler is above GPBase and so is free to any program that has a GP block already --
;		and one with a GP.DO in it does.
;
; ************************************************************************************************

CommandXUnwind: ;; [.unwind]
		.entercmd
		;
		;		NXCommand consumes the opcode byte before it dispatches, so Y ALREADY points at
		;		the operand on entry -- one iny here and the count read is the byte after it.
		;		The single iny below is what leaves Y on the next opcode for NextCommand.
		;
		lda 	(codePtr),y 				; the count
		sta 	unwindLeft
		iny 								; past it, where execution resumes
		lda 	unwindLeft
		beq 	_CXUDone 					; nothing to close, which is the common case
_CXULoop:
		lda 	(runtimeStackPtr) 			; the frame marker on top
		cmp 	#$FF 						; the stack-empty marker -- go no further
		beq 	_CXUDone
		and 	#$E0 						; the id is the upper 3 bits (frames.inc)
		cmp 	#FRAME_LOOP & $E0 			; GP.DO is the only block frame there is now --
		bne 	_CXUStray 					; GP.SELECT stopped opening one on 01/09/26, and a
		dec 	unwindLeft 					; FOR or GOSUB frame is closed but never counted
_CXUStray:
		jsr 	StackCloseFrame
		lda 	unwindLeft
		bne 	_CXULoop
_CXUDone:
		.exitcmd

		.send 	code

; ************************************************************************************************
;
;		Blocks still to close. In the storage section, which lives in the $0400-$0801 hole BELOW
;		the object's load address -- so it is uninitialised RAM at run time and not a byte in the
;		file. See the .cerror in common.inc that guards the hole from overflowing.
;
; ************************************************************************************************

		.section storage
unwindLeft:
		.fill 	1
		.send 	storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;		31/08/26		Written.
;
; ************************************************************************************************
