# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		genmapping.py
#		Purpose :	Create words that call functionality.
#		Date :		11th April 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************
#
#		Columns are : Operator, Function and Check Carry on Exit
#
mappings = """
		+		FloatAdd
		- 		FloatSubtract
		* 		FloatMultiply
		/ 		FloatDivide 				*
		^ 		FloatPower 					*
		>		CompareGreater
		=		CompareEqual
		<		CompareLess
		>=		CompareGreaterEqual
		<>		CompareNotEqual
		<=		CompareLessEqual
		int 	FloatIntegerPartDown
		sqr 	FloatSquareRoot 			*
		log 	FloatLogarithm 				*
		exp 	FloatExponent
		cos		FloatCosine
		sin 	FloatSine
		tan 	FloatTangent
		atn		FloatArcTan 				*
		f.cmp 	FloatCompare
		int.div DivideInt32 				*
"""

#
#		The polynomials run from bank 1 (HANDLER_BANK), and so do their wrappers, which leave through
#		.exitbank. A bcs cannot reach low RAM from $A000, so a banked wrapper steps over a jmp to the
#		error. Each wrapper opens its own section, which keeps the markers in order and the opcode
#		numbers unchanged.
#
polynomials = ["^","sqr","log","exp","cos","sin","tan","atn"]

mappings = [x.strip() for x in mappings.split("\n") if x.strip() != ""]

print(";\n;\tThis file is automatically generated\n;")

for m in mappings:
	m = m.split()
	section = "banked" if m[0] in polynomials else "code"
	error = "DivZeroError" if m[0] == "/" else "MapRangeError"
	toShift = "!" if len(m[0]) == 3 else ""
	print("\t.section {0}".format(section))
	print("Link{0}: ;; [{1}]".format(m[1],toShift+m[0]))
	print("\t.entercmd")
	print("\tphy")
	print("\tjsr\t{0}".format(m[1]))
	if len(m) == 3 and section == "banked":
		print("\tbcc\t_Result")
		print("\tjmp\t{0}".format(error))
		print("_Result:")
	if len(m) == 3 and section == "code":
		print("\tbcs\t{0}".format(error))
	print("\tply")
	print("\t.exitbank" if section == "banked" else "\t.exitcmd")
	print("\t.send {0}".format(section))

	if m[0] == "sqr":
		print("\t.section code")
		print("MapRangeError:")
		print("\t.error_range")
		print("DivZeroError:")
		print("\t.error_divzero")
		print("\t.send code")
