# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		vectors.py
#		Purpose :	Generate vector table
#		Date :		12th April 2023
#		Author : 	Paul Robson .paul@robsons.org.uk
#
# *******************************************************************************************
# *******************************************************************************************

import os,re,sys
from pcode import *
from build import * 

#
#		Both runtime trees, not just this one: the GP handlers live in ../gp-runtime so they can be
#		linked last (see getRuntimeASMFiles). Scanning only "." here would leave every GP opcode
#		pointing at Unimplemented -- and silently, because a missing marker is not an error below.
#
#		A handler in the banked section runs from bank 1 (HANDLER_BANK). Its entry in the low table is
#		BankEnter, or BankEnterShift in the shifted table (source/main/00runtime.asm), and its address goes
#		in a copy of the table in the banked section. A copy runs from the first banked opcode to the last.
#		BankVectors and BankShiftVectors are placed so that the X the dispatcher left indexes the copy as
#		it indexes the low table. A gap in a copy is never entered and holds Unimplemented.
#
vectors = {}
banked = set()
for f in getRuntimeASMFiles():
	section = None
	for s in open(f).readlines():
		m = re.match("^\\s*\\.section\\s+(\\w+)",s)
		if m is not None:
			section = m.group(1)
		if re.match("^\\s*\\.send",s) is not None:
			section = None
		if s.find(";;") >= 0:
			m = re.match("^(.*?)\\:\\s*\\;\\;\\s*\\[(.*)\\]\\s*$",s)
			assert m is not None,"Bad line "+s
			v = m.group(2).lower()
			v = v[1:] if v.startswith("!") else v
			vectors[v] = m.group(1)
			if section == "banked":
				banked.add(v)

pcodes = PCode().idToToken
ids = [x for x in pcodes.keys()]
ids.sort()

def handler(i):
	return vectors[pcodes[i]] if pcodes[i] in vectors else "Unimplemented"

def entry(label,i,note = ""):
	print("\t.word\t{0:24} ; ${1:02x} {2}{3}".format(label,i,pcodes[i].lower(),note))

def bankTable(table,base,tableIDs):
	moved = [i for i in tableIDs if pcodes[i] in banked]
	assert len(moved) > 0,"No banked handler for "+table
	print("\n{0}:".format(table))
	for i in tableIDs:
		if i >= moved[0] and i <= moved[-1]:
			entry(handler(i) if pcodes[i] in banked else "Unimplemented",i)
	print("{0} = {1} - ${2:02x}".format(base,table,(moved[0] & 0x7F) * 2))

print(";\n;\tThis file is automatically generated\n;")
print("\t.section code")
print("VectorTable:")
for i in ids:
	if i > 256 and (i & 0xFF) == 0x80:
		print("\n\nShiftVectorTable:")
	if pcodes[i] in banked:
		entry("BankEnterShift" if i > 256 else "BankEnter",i,", "+handler(i)+" in bank 1")
	else:
		entry(handler(i),i)
print("\t.send code")

print("\n\t.section banked")
bankTable("BankVectorTable","BankVectors",[i for i in ids if i < 256])
bankTable("BankShiftVectorTable","BankShiftVectors",[i for i in ids if i > 256])
print("\t.send banked")
