;
;	This file is automatically generated
;
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		api.asm
;		Purpose:	Compiler API Interface
;		Created:	9th October 2023
;		Reviewed: 	No
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

; ************************************************************************************************
;
;									API Entry point
;
; ************************************************************************************************

		.section code

CompilerAPI:
		cmp 	#BLC_OPENIN
		beq 	_CAOpenIn
		cmp 	#BLC_CLOSEIN
		beq 	_CACloseIn
		cmp 	#BLC_READIN
		beq 	_CARead
		cmp 	#BLC_RESETOUT
		beq 	_CAResetOut
		cmp 	#BLC_CLOSEOUT
		beq 	_CACloseOut
		cmp 	#BLC_WRITEOUT
		beq 	_CAWriteByte
		cmp 	#BLC_PRINTCHAR
		beq 	_CAPrintScreen
		.debug

; ************************************************************************************************
;
;									Open source file for reading
;
; ************************************************************************************************

_CAOpenIn:	
		ldy 	#SourceFile >> 8 			; name of file
		ldx 	#SourceFile & $FF		
		jsr 	IOOpenRead 					; open file
		jsr 	IOReadByte 					; skip the 2 byte load address header
		jsr 	IOReadByte
		rts

; ************************************************************************************************
;
;									Close read source file
;
; ************************************************************************************************

_CACloseIn:
		jmp 	IOReadClose

; ************************************************************************************************
;
;								Code is stored from free memory onwards
;
; ************************************************************************************************

_CAResetOut:
		.set16 	objPtr,FreeMemory
		rts

_CACloseOut:
		rts

; ************************************************************************************************
;
;									Write byte A to free memory
;
; ************************************************************************************************

_CAWriteByte:
		txa
		sta 	(objPtr)
		inc 	objPtr
		bne 	_HWOWBNoCarry
		inc 	objPtr+1
_HWOWBNoCarry:		
		rts

; ************************************************************************************************
;
;								Print character to screen
;
; ************************************************************************************************
		
_CAPrintScreen:
		txa
		jmp 	$FFD2

; ************************************************************************************************
;
;									  Read line
;
; ************************************************************************************************

_CARead:
		jsr 	IOReadByte 				; copy the address of next into the buffer
		sta 	SourceLine+0
		jsr 	IOReadByte
		sta 	SourceLine+1
		;
		ora 	sourceLine				; if both were zero, exit with CC (e.g. fail)
		clc
		beq		_CARExit

		jsr 	IOReadByte 				; read the line # into the buffer.
		sta 	SourceLine+2
		jsr 	IOReadByte
		sta 	SourceLine+3
		;
		ldx 	#4 						; read the body of the line.
_CAReadLine:
		jsr 	IOReadByte 				; now keep copying to EOL
		sta 	SourceLine,x
		inx
		cmp 	#0
		bne 	_CAReadLine
		;		
		sec 							; read a line okay
		ldy 	#SourceLine >> 8
		ldx 	#SourceLine & $FF
_CARExit:		
		rts


;;		ldy 	#ObjectFile >> 8
;		ldx 	#ObjectFile & $FF		
;		jsr 	IOOpenWrite
;		lda 	#12
;		jsr 	IOWriteByte
;		lda 	#13
;		jsr 	IOWriteByte
;		jsr 	IOWriteClose
				
SourceLine: 								; line for source code storage. In the code section, not
		.fill 	256 						; storage: see the note in file-io/read.asm -- this was
											; the single biggest thing in a 1K hole that had run
											; out of room.
		.send code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************

; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		control.asm
;		Purpose:	The compiler's control file, GPC.INPUT
;		Created:	14th July 2026
;		Reviewed: 	No
;
; ************************************************************************************************
; ************************************************************************************************
;
;		The compiler had SOURCE.PRG and OBJECT.PRG built into it, so the only way to point it at
;		a program was to rename files around it. It now reads GPC.INPUT, a plain text file of
;		three lines, which is what lets another program drive it:
;
;			DIR.PRG				line 1	the tokenised BASIC to compile
;			C.DIR.PRG			line 2	the object file to write
;								line 3	options. Read, but ignored for now.
;
;		A line ends at CR, at LF, or at anything else below a space, and an empty line is
;		skipped -- so a control file written on a CRLF host is as good as one written on the X16.
;
;		Lowercase is folded to upper. A name typed in ASCII lowercase is not the PETSCII the
;		KERNAL wants, and it is the mistake a caller will actually make; the host filesystems
;		this runs on are all case insensitive, so folding can only ever help.
;
;		There is no fallback. Without a readable GPC.INPUT the compiler says NO GPC.INPUT FILE
;		and stops, because a compiler that guesses at what it was asked to build is worse than
;		one that refuses.
;
; ************************************************************************************************

CFLineSize = 64 							; the three lines are ONE 192 byte block, so a single
											; 8 bit index walks all of them. Nothing else works:
											; three separate buffers would need a pointer, and
											; the KERNAL calls in here are free to trash one.

		.section code

; ************************************************************************************************
;
;		Read GPC.INPUT into SourceFile, ObjectFile and OptionsText.
;
;		Returns carry SET if there was no usable control file.
;
; ************************************************************************************************

ReadControlFile:
		lda 	#0 							; blank all three lines. This is what puts the zero
		ldx 	#CFLineSize*3-1 			; terminator on the end of each of them, and what
_RCFBlank: 									; leaves a short control file holding empty strings
		sta 	SourceFile,x 				; rather than whatever happened to be in memory.
		dex
		bpl 	_RCFBlank

		ldy 	#ControlFile >> 8
		ldx 	#ControlFile & $FF
		jsr 	IOOpenRead
		ldx 	#0 							; X walks the three lines as one block (preserves C)
		bcs 	_RCFClose 					; carry set means we have no input channel, and then
											; reading is NOT harmless: CHRIN would fall back to
											; the keyboard and sit there waiting to be typed at.
_RCFRead:
		jsr 	IOReadByte 					; carry set at end of file
		bcs 	_RCFClose

		cmp 	#' ' 						; CR, LF, and anything else below a space, ends the
		bcc 	_RCFEndOfLine 				; line

		cmp 	#$C1 						; PETSCII shifted letters, which is what the X16 hands
		bcc 	_RCFNotShifted 				; you if you type the name with SHIFT held down. CBM
		cmp 	#$DB 						; DOS wants the UNshifted ones in a filename, and they
		bcs 	_RCFNotShifted 				; are a different character entirely, not a case.
		and 	#$7F 						; $C1-$DA -> $41-$5A
		bra 	_RCFStore
_RCFNotShifted:
		cmp 	#'a' 						; and ASCII lowercase, which is what a text editor on
		bcc 	_RCFStore 					; the host gives you
		cmp 	#'z'+1
		bcs 	_RCFStore
		and 	#$DF 						; $61-$7A -> $41-$5A
_RCFStore:
		pha
		txa 								; the last byte of a line is its zero terminator and
		and 	#CFLineSize-1 				; is never written to, so an over-long name is
		cmp 	#CFLineSize-1 				; truncated rather than left to run on into the next
		pla 								; line.
		bcs 	_RCFRead
		sta 	SourceFile,x
		inx
		bra 	_RCFRead

_RCFEndOfLine:
		txa
		and 	#CFLineSize-1 				; nothing on this line yet ? then this is the LF of a
		beq 	_RCFRead 					; CRLF, or a blank line -- there is nothing to end.
		txa 								; otherwise step X on to the start of the next line.
		clc
		adc 	#CFLineSize
		and 	#$100-CFLineSize
		tax
		cpx 	#CFLineSize*3 				; stop at three lines, whatever else the file holds
		bcc 	_RCFRead

_RCFClose:
		jsr 	IOReadClose 				; close it either way. Logical file 3 is the one the
											; source is read on, so it has to be free.
		sec
		lda 	SourceFile 					; no source name means there was no usable control
		beq 	_RCFFail 					; file: missing, empty, or a first line we could not
		lda 	ObjectFile 					; use. No object name is just as useless -- we would
		beq 	_RCFFail 					; have nowhere to put the answer.
		clc
_RCFFail:
		rts

; ************************************************************************************************
;
;		"GPC SQUEALING..." then the two names, each on its own labelled line -- the whole of the
;		compiler's startup output. Three short lines so nothing wraps in 40 columns.
;
;			GPC SQUEALING...
;			in:  <source>
;			out: <object>
;
; ************************************************************************************************

PrintWorking:
		ldx 	#WorkingText & $FF 			; "GPC SQUEALING...",CR
		ldy 	#WorkingText >> 8
		jsr 	PrintMessage
		ldx 	#InText & $FF 				; "in:  "
		ldy 	#InText >> 8
		jsr 	PrintMessage
		ldx 	#0 							; line 1, the source
		jsr 	PrintControlLine
		ldx 	#OutText & $FF 				; CR then "out: "
		ldy 	#OutText >> 8
		jsr 	PrintMessage
		ldx 	#CFLineSize 				; line 2, the object
		jsr 	PrintControlLine
		lda 	#13
		jmp 	$FFD2

; ************************************************************************************************
;
;								There was nothing to work from
;
; ************************************************************************************************

PrintNoControlFile:
		ldx 	#NoControlText & $FF
		ldy 	#NoControlText >> 8
		jmp 	PrintMessage

; ************************************************************************************************
;
;								Print the ASCIIZ string at YX
;
; ************************************************************************************************

PrintMessage:
		stx 	zTemp0
		sty 	zTemp0+1
		ldy 	#0
_PMLoop:
		lda 	(zTemp0),y
		beq 	_PMExit
		phy 								; CHROUT makes no promise about Y
		jsr 	$FFD2
		ply
		iny
		bne 	_PMLoop
_PMExit:
		rts

; ************************************************************************************************
;
;							Print the ASCIIZ control line at offset X
;
; ************************************************************************************************

PrintControlLine:
_PCLLoop:
		lda 	SourceFile,x
		beq 	_PCLExit
		phx
		jsr 	$FFD2
		plx
		inx
		bra 	_PCLLoop
_PCLExit:
		rts

; ************************************************************************************************
;
;										Fixed text
;
; ************************************************************************************************

ControlFile:
		.text 	'GPC.INPUT',0
WorkingText:
		.text 	'GPC SQUEALING...',13,0
InText: 									; uppercase: the screen boots in PETSCII upper/graphics, where
		.text 	'IN:  ',0 				; lowercase bytes are graphics glyphs, not letters
OutText: 									; the CR ends the source line and starts the object's
		.text 	13,'OUT: ',0
NoControlText:
		.text 	'NO GPC.INPUT FILE',13,0

; ************************************************************************************************
;
;		The three lines of GPC.INPUT, laid out as one contiguous block -- see CFLineSize above.
;
;		These are buffers, but they are deliberately NOT in the storage section. That section is
;		a .dsection at $0400 (common.inc) and the code starts at $0801, so it is a 1K hole -- and
;		it was already full. Everything here belongs to the compiler, which lives above
;		ObjectBase and is thrown away when the object code is written, so a buffer here costs a
;		compiled program nothing at all. See the note in file-io/read.asm.
;
; ************************************************************************************************

SourceFile: 								; line 1 : what to compile
		.fill 	CFLineSize
ObjectFile: 								; line 2 : where to write it
		.fill 	CFLineSize
OptionsText: 								; line 3 : read and thrown away for now, so that a
		.fill 	CFLineSize 					; caller can already write options that will one day
											; be honoured.

		.send code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		object.asm
;		Purpose:	Write object code out.
;		Created:	9th October 2023
;		Reviewed: 	No
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section code

; ************************************************************************************************
;
;									Write object code out.
;
; ************************************************************************************************

;
;		Pages left free below the workspace for the runtime (GOSUB/FOR) stack. clr.asm puts
;		runtimeStackPtr at storeStartHigh-1:$FF and grows it DOWNWARD, so without a gap here
;		a deep call chain would walk straight back into the object code.
;
FrameStackPages = 16 						; 4K, ~250 frames

; ************************************************************************************************
;
;		Write object code out.
;
;		In memory the layout is
;
;			$0801 [ runtime ] ObjectBase [ compiler ] FreeMemory [ object code ] objPtr
;
;		but a saved program never compiles anything, so the compiler is dead weight. The
;		file is therefore written in two pieces -- the runtime, then the object code -- so
;		that on reload the object code lands at ObjectBase, on top of where the compiler was.
;
;		That reclaims (FreeMemory-ObjectBase) bytes from every compiled program, and, more
;		importantly, lets the workspace start just above the object code instead of at a
;		hardcoded $8000 -- which is most of the useable memory a compiled program gets.
;
;		The two immediates in StartCode are patched as they stream past, rather than in RAM,
;		so the copy still in memory (RUN a second time) keeps running from FreeMemory.
;
; ************************************************************************************************

WriteObjectCode:
		jsr 	PatchOutCompile 			; makes it run the runtime on reload
		;
		;		zTemp1 = length of the object code.
		;
		sec
		lda 	objPtr
		sbc 	#FreeMemory & $FF
		sta 	zTemp1
		lda 	objPtr+1
		sbc 	#FreeMemory >> 8
		sta 	zTemp1+1
		;
		;		Round that up to whole pages.
		;
		lda 	zTemp1 						; any part page ?
		beq 	_WOCWholePages
		inc 	zTemp1+1 					; then it needs one more
_WOCWholePages:
		;
		;		newWorkspacePage = ObjectBase + pages(object code) + the frame stack gap.
		;
		clc
		lda 	#ObjectBase >> 8
		adc 	zTemp1+1
		adc 	#FrameStackPages
		sta 	newWorkspacePage

		ldy 	#ObjectFile >> 8
		ldx 	#ObjectFile & $FF
		jsr 	IOOpenWrite 				; open write

		lda 	#1 							; write out the load address $0801
		jsr 	IOWriteByte
		lda 	#8
		jsr 	IOWriteByte
		;
		;		Part one : the runtime, $0801 up to ObjectBase, patching the two immediates
		;		in StartCode on the way past.
		;
		.set16 	zTemp0,StartBasicProgram
_WOCRuntime:
		lda 	zTemp0+1 					; the code page operand ?
		cmp 	#(RunCodePage+1) >> 8
		bne 	_WOCNotCodePage
		lda 	zTemp0
		cmp 	#(RunCodePage+1) & $FF
		bne 	_WOCNotCodePage
		lda 	#ObjectBase >> 8 			; object code moves down to here
		bra 	_WOCEmit
_WOCNotCodePage:
		lda 	zTemp0+1 					; the workspace page operand ?
		cmp 	#(RunWorkspacePage+1) >> 8
		bne 	_WOCPlain
		lda 	zTemp0
		cmp 	#(RunWorkspacePage+1) & $FF
		bne 	_WOCPlain
		lda 	newWorkspacePage 			; so the workspace can start much lower
		bra 	_WOCEmit
_WOCPlain:
		lda 	(zTemp0)
_WOCEmit:
		jsr 	IOWriteByte
		inc 	zTemp0
		bne 	_WOCSkip1
		inc 	zTemp0+1
_WOCSkip1:
		lda 	zTemp0+1 					; until we reach ObjectBase (page aligned)
		cmp 	#ObjectBase >> 8
		bne 	_WOCRuntime
		lda 	zTemp0
		cmp 	#ObjectBase & $FF
		bne 	_WOCRuntime
		;
		;		Part two : the object code itself, which lands at ObjectBase on reload.
		;
		.set16 	zTemp0,FreeMemory
_WOCCode:
		lda 	zTemp0 						; done ?
		cmp 	objPtr
		bne 	_WOCCodeByte
		lda 	zTemp0+1
		cmp 	objPtr+1
		beq 	_WOCDone
_WOCCodeByte:
		lda 	(zTemp0)
		jsr 	IOWriteByte
		inc 	zTemp0
		bne 	_WOCCode
		inc 	zTemp0+1
		bra 	_WOCCode
_WOCDone:
		jsr 	IOWriteClose 				; close the file.
		rts

; ************************************************************************************************
;
;		Write the debug MAP file, if GPC.INPUT gave a third line (its name). The map turns a
;		runtime error's "@ $XXXX" back into a source line, which is otherwise a hand decode of
;		the p-code. One text line per source line, in ascending code order:
;
;			0030 12
;
;		the 4-digit hex P-CODE OFFSET -- exactly what the runtime prints as "@ $0030" -- then a
;		space and the DECIMAL BASIC line number that begins there. To place an error, find the
;		largest offset that is <= the one reported.
;
;		It is built straight from the compiler's line-number table (STRMarkLine): 4-byte entries
;		[line# lo, line# hi, addr lo, addr hi], growing DOWNWARD from compilerEndHigh:$00 to
;		lineNumberTable, walked here from the top down so the file comes out in code order. The
;		stored addr is the compile-time position in the object buffer (based at FreeMemory), so
;		offset = addr - FreeMemory -- the same number the runtime reports, because the object is
;		copied verbatim from FreeMemory to its run address. The two synthetic lines the implicit
;		-DIM prologue adds show up as line 65024 ($FE00, the end marker) and 65535 ($FFFF, the
;		prologue); they are real code positions, just not the user's.
;
; ************************************************************************************************

WriteMapFile:
		lda 	OptionsText 				; no third line -> no map asked for.
		bne 	_WMFStart
		rts
_WMFStart:
		ldy 	#OptionsText >> 8 			; open the map file for write (logical file 3, as the
		ldx 	#OptionsText & $FF 			; object write already closed).
		jsr 	IOOpenWrite
		lda 	compilerEndHigh 			; walk from the top of the table ...
		sta 	mapWalk+1
		stz 	mapWalk
_WMFLoop:
		sec 								; ... down one 4-byte entry at a time.
		lda 	mapWalk
		sbc 	#4
		sta 	mapWalk
		lda 	mapWalk+1
		sbc 	#0
		sta 	mapWalk+1
		lda 	mapWalk+1 					; stop once below the last (lowest) entry.
		cmp 	lineNumberTable+1
		bcc 	_WMFDone
		bne 	_WMFEntry
		lda 	mapWalk
		cmp 	lineNumberTable
		bcc 	_WMFDone
_WMFEntry:
		jsr 	_WMFWriteEntry
		bra 	_WMFLoop
_WMFDone:
		jmp 	IOWriteClose

;
;		Write one entry: "<hhhh> <ddddd>",CR. Everything the line needs is pulled out through
;		zTemp0 up front, before any IOWriteByte -- CHROUT to a file is free to trash zero page,
;		but mapValue/mapOff are plain RAM and survive it.
;
_WMFWriteEntry:
		lda 	mapWalk 					; point zTemp0 at the entry.
		sta 	zTemp0
		lda 	mapWalk+1
		sta 	zTemp0+1
		ldy 	#0 							; line number -> mapValue (consumed by the decimal print)
		lda 	(zTemp0),y
		sta 	mapValue
		ldy 	#1
		lda 	(zTemp0),y
		sta 	mapValue+1
		ldy 	#2 							; offset = stored address - FreeMemory (page aligned)
		lda 	(zTemp0),y
		sec
		sbc 	#FreeMemory & $FF
		sta 	mapOff
		ldy 	#3
		lda 	(zTemp0),y
		sbc 	#FreeMemory >> 8
		sta 	mapOff+1
		lda 	mapOff+1 					; hex offset, high byte then low.
		jsr 	_WMFHexByte
		lda 	mapOff
		jsr 	_WMFHexByte
		lda 	#' '
		jsr 	IOWriteByte
		jsr 	_WMFDecimal 				; decimal line number.
		lda 	#10 						; LF ends the line -- this file is read on the host (grep,
		jmp 	IOWriteByte 				; VS Code), not the X16, so a Unix newline suits it best.

;
;		A (0..255) as two hex digits. Same trick as the runtime error handler.
;
_WMFHexByte:
		pha
		lsr 	a
		lsr 	a
		lsr 	a
		lsr 	a
		jsr 	_WMFNibble
		pla
_WMFNibble:
		and 	#15
		cmp 	#10
		bcc 	_WMFDigit
		adc 	#6 							; carry set here: 10 -> +6+1 = 'A'
_WMFDigit:
		adc 	#48
		jmp 	IOWriteByte

;
;		mapValue (16 bit) as decimal, leading zeros suppressed but always at least one digit.
;		Subtract each power of ten as many times as it goes; the count is the digit.
;
_WMFDecimal:
		stz 	mapLead 					; 0 while we are still dropping leading zeros
		ldx 	#0
_WMFDPow:
		ldy 	#48 						; '0' + number of subtractions = the digit
_WMFDSub:
		sec
		lda 	mapValue
		sbc 	_WMFPow10L,x
		sta 	mapTemp
		lda 	mapValue+1
		sbc 	_WMFPow10H,x
		bcc 	_WMFDUnder 					; borrow -> this power no longer goes
		sta 	mapValue+1
		lda 	mapTemp
		sta 	mapValue
		iny
		bra 	_WMFDSub
_WMFDUnder:
		cpy 	#48 						; a zero digit ...
		bne 	_WMFDEmit
		lda 	mapLead 					; ... is dropped while still leading
		beq 	_WMFDNext
_WMFDEmit:
		lda 	#1
		sta 	mapLead
		tya
		jsr 	IOWriteByte
_WMFDNext:
		inx
		cpx 	#4 							; 10000, 1000, 100, 10
		bne 	_WMFDPow
		lda 	mapValue 					; the units digit is always written
		ora 	#48
		jmp 	IOWriteByte

_WMFPow10L:
		.byte 	<10000, <1000, <100, <10
_WMFPow10H:
		.byte 	>10000, >1000, >100, >10

newWorkspacePage: 							; first page of workspace in the saved file. In the code
		.fill 	1 							; section, not storage -- see the note in
											; file-io/read.asm.
mapWalk: 									; these too live in the code section, not storage -- they
		.fill 	2 							; belong to the compiler and are thrown away when the
mapValue: 									; object is written, so they cost a compiled program
		.fill 	2 							; nothing. See the note in file-io/read.asm.
mapOff:
		.fill 	2
mapTemp:
		.fill 	2
mapLead:
		.fill 	1
		.send code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		read.asm
;		Purpose:	Read file code.
;		Created:	9th October 2023
;		Reviewed: 	No
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section code

; ************************************************************************************************
;
;								 Open sequential file for Read
; 									   YX = ASCIIZ name
;
; ************************************************************************************************

IOOpenRead:
		lda 	#'R' 						; read.
		jsr 	IOSetFileName 				; set up name/LFS
		ldx	 	#3 							; use file 3 for reading
		jsr 	$FFC6 						; CHKIN
		rts

; ************************************************************************************************
;
;									Read A from input file
;
;			    If read,  A=Byte and Carry Clear, else A = Error and Carry Set
;
; ************************************************************************************************

IOReadByte:
		phx 					
		phy
		jsr 	$FFB7 						; read ST
		sec
		bne 	_IORExit
		jsr 	$FFCF 						; read a byte
		clc 								; status OK.
_IORExit:		
		ply
		plx
		rts

; ************************************************************************************************
;
;							    Close files (use the same code)
;
; ************************************************************************************************

IOReadClose:
IOWriteClose:
		lda 	#3 							; CLOSE# 3
		jsr 	$FFC3
		jsr 	$FFCC 						; CLRCHN
		rts

; ************************************************************************************************
;
;				 Set LFS, Name and Open File. YX = Filename (ASCIIZ) A = R/W
;
; ************************************************************************************************

IOSetFileName:
		pha 								; save R/W
		stx 	zTemp0
		sty 	zTemp0+1
		ldy 	#$FF 						; copy name given
_IOSCopy:
		iny 								; pre-increment copy
		lda 	(zTemp0),y
		sta 	IONameBuffer,y
		bne 	_IOSCopy
		;
		pla 								; recover R/W
		cmp 	#'W'
		bne 	_IOSRead 					; reading uses the PLAIN name -- see the note below
		lda 	#',' 						; writing appends ",S,W" to create the file
		sta 	IONameBuffer+0,y
		sta 	IONameBuffer+2,y
		lda 	#'S'
		sta 	IONameBuffer+1,y
		lda 	#'W'
		sta 	IONameBuffer+3,y
		lda 	#0 							; terminator after the suffix
		sta 	IONameBuffer+4,y
		tya 								; name length plus the four we appended
		clc
		adc 	#4
		bra 	_IOSSetName
_IOSRead:
		tya 								; READ: the length is just the name -- NO ",S,R". Box16's
											; -hypercall_path opens the raw SETNAM string, so a
											; ",S,R" suffix makes it hunt for a host file literally
											; called "NAME,S,R" and the open fails. A plain name
											; reads on x16emu, Box16 and real CMDR-DOS alike (x16emu
											; only tolerated the suffix by parsing it off first).
											; Writing still needs ",S,W", which Box16 does honour.
_IOSSetName:
 								
		ldx 	#IONameBuffer & $FF			; name address to YX
		ldy 	#IONameBuffer >> 8

	    jsr 	$FFBD          				; call SETNAM

    	lda 	#3 							; set LFS to 3,8,3
		ldx 	#8
		ldy 	#3
		jsr 	$FFBA		

		jsr 	$FFC0 						; OPEN
		rts

; ************************************************************************************************
;
;		The name, with ",S,R" or ",S,W" appended.
;
;		This was 64 bytes in the storage section, and that was a loaded gun. storage is a
;		.dsection at $0400 with the code starting at $0801 (common.inc), so it is a 1K hole --
;		and it was already full to the last byte. IONameBuffer sat at $07F1, which left it room
;		for exactly "SOURCE.PRG,S,R" and its terminator: fifteen bytes, ending at $07FF. Any
;		name longer than that would have written straight over the BASIC stub at $0801 and
;		destroyed the program that was running.
;
;		Nobody noticed because the two names were hardcoded and both were ten characters. Now
;		that GPC.INPUT supplies them, they can be any length, so the buffer is here in the code
;		section instead -- which is the compiler, above ObjectBase, thrown away when the object
;		code is written. It costs a compiled program nothing.
;
; ************************************************************************************************

IONameBuffer:
		.fill 	CFLineSize+8 				; the longest line GPC.INPUT can hold, plus ",S,R"
											; and the zero
		.send code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		start.asm
;		Purpose:	Start actual compilation.
;		Created:	9th October 2023
;		Reviewed: 	No
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section code

; ************************************************************************************************
;
;									Compile the code from disk
;
; ************************************************************************************************

CompileCode:
		jsr 	ReadControlFile 			; GPC.INPUT says what to compile and where to put it
		bcs 	_CCNoControlFile 			; and without it there is nothing to be done
		jsr 	PrintWorking 				; which is all the compiler now says for itself

		ldx 	#APIDesc & $FF
		ldy 	#APIDesc >> 8
		jsr 	StartCompiler
		jsr 	WriteObjectCode
		jsr 	WriteMapFile 				; and the line#->offset map, if GPC.INPUT asked for one
		lda 	#"O" 						; the only other thing it prints, and the only way a
		jsr 	$FFD2 						; caller can tell a compile that worked from one that
		lda 	#"K" 						; stopped on an error, so it stays.
		jsr 	$FFD2
		rts

_CCNoControlFile: 							; a compiler that guesses at what it was asked to
		jmp 	PrintNoControlFile 			; build is worse than one that refuses

; ************************************************************************************************
;
;									API Setup for the compiler
;
; ************************************************************************************************

APIDesc:
		.word 	CompilerAPI 				; the compiler API Implementeation
		.byte 	$80 						; start of workspace for compiler $8000
		.byte 	$9F							; end of workspace for compiler $9F00

;
;		The source and object file names used to be two .text constants here. They are now the
;		first two lines of GPC.INPUT -- see file-io/control.asm.
;

		.send code

		.section storage
		.send storage

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
; ************************************************************************************************
; ************************************************************************************************
;
;		Name:		write.asm
;		Purpose:	Write file code
;		Created:	9th October 2023
;		Reviewed: 	No
;		Author:		Paul Robson (paul@robsons.org.uk)
;
; ************************************************************************************************
; ************************************************************************************************

		.section code

; ************************************************************************************************
;
;								Open sequential file for Write.
; 									   YX = ASCIIZ name
;
; ************************************************************************************************

IOOpenWrite:
		lda 	#'W'			 			; write
		jsr 	IOSetFileName 				; set up name/LFS
		ldx	 	#3 							; use file 3 for writing
		jsr 	$FFC9 						; CHKOUT
		rts

; ************************************************************************************************
;
;									Write A to output file
;
; ************************************************************************************************

IOWriteByte:		
		pha
		phx
		phy
		jsr 	$FFD2
		ply
		plx
		pla
		rts

		.send code

; ************************************************************************************************
;
;									Changes and Updates
;
; ************************************************************************************************
;
;		Date			Notes
;		==== 			=====
;
; ************************************************************************************************
