# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		mathconstants.py
#		Purpose :	Constants for trig/log functions.
#		Date :		11th April 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math

from floats import *

constants = {}
constants["1Div2Pi"] = 1.0 / (2 * math.pi)
constants["PiDiv2"] = math.pi / 2.0
constants["Log2_e"] = math.log(math.e,2.0)
constants["sqrt_2"] = math.sqrt(2.0)
constants["sqrt_half"] = math.sqrt(0.5)
constants["pi"] = math.pi 
constants["half"] = 0.5 
constants["ln_e"] =	math.log(2,math.e)

f = Float()

h = open("source/generated/constants.asm","w")
h.write(";\n;\tThis file is automatically generated.\n;\n")
h.write(".section code\n")
h.write("Const_Base:\n")
#
#	Six bytes per constant: mantissa, exponent, sign. The sign gets a byte to itself because the
#	mantissa is a full 32 bits now (see floats.py / FloatNormalise) and bit 31 is no longer spare
#	to carry it -- LoadConstant used to mask that bit off, which halved every constant and made it
#	negative. All of these happen to be positive, but emit the byte properly rather than rely on it.
#
for name in constants.keys():
	ed = f.toFloat(constants[name])
	h.write("Const_{0}:\n".format(name))
	h.write("\t.dword\t${0:08x} ; {1:.8f}\n".format(ed[0],constants[name]))
	h.write("\t.byte\t${0:02x}\n".format(ed[1]))
	h.write("\t.byte\t${0:02x}\n".format(ed[2]))
h.write(".send code\n")

h.close()	
