# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		bumpbuild.py
#		Purpose :	Generate source/generated/version.asm from the two version stamps
#		Date :		30th July 2026
#
# *******************************************************************************************
# *******************************************************************************************
#
#		TWO STAMPS, because they answer two different questions.
#
#			buildnum.txt   the PRODUCT VERSION, e.g. "1.0.0". Printed by GPC.BIN as
#			               V1.0.0 and used by release.sh to name the release zip. Changed by
#			               hand when a release is cut, and by nothing else.
#
#			rtbuild.txt    the RUNTIME BUILD NUMBER, e.g. 120. This is the nnn in
#			               GPC.RT.nnn.BIN -- the shared runtime's file name, which
#			               bootstrap.asm formats from the BuildNumber symbol below and
#			               rtname.py formats from the same file. STATIC, on purpose.
#
#		WHY THEY ARE SEPARATE, AND WHY NOTHING BUMPS ANY MORE. The build number used to be the
#		last component of buildnum.txt and incremented on EVERY engine build. That answered
#		"am I running my fix?" nicely, and broke the shared runtime: the runtime's file name
#		carries the number, so every rebuild produced a differently-named GPC.RT file and every
#		program compiled against the old name stopped finding its runtime. A project consuming
#		GPC in shared mode -- which is what the game does -- needs that name to hold still.
#
#		So the number is pinned and edited deliberately. Move it only when a shared-mode
#		program must be forced to pick up a new runtime, and remember that every such program
#		has to be recompiled: the name is baked into each object by bootstrap.asm.
#
#		This is NOT the ABI ordinal. RT_ABI (common.inc) is that, in the 4-byte magic at
#		RTBASE, and answers the different question of whether an already-resident runtime can
#		safely be entered. The file name says WHICH runtime; the magic says whether it FITS.
#
#		--bump is still accepted and does nothing but say so, because release.sh and
#		source/Makefile have carried the flag through several revisions and a hard error here
#		would fail a build over a no-op.
#
# *******************************************************************************************

import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)								# source/application
STAMP = os.path.join(APP, "buildnum.txt")				# product version, e.g. 1.0.0
RTSTAMP = os.path.join(APP, "rtbuild.txt")				# runtime build number, e.g. 120
GENDIR = os.path.join(APP, "source", "generated")
OUT = os.path.join(GENDIR, "version.asm")


def die(msg):
	sys.exit("  bumpbuild: FAIL -- " + msg)


def read(path, what):
	if not os.path.isfile(path):
		die("%s is missing -- it holds the %s and is tracked in git" % (path, what))
	return open(path, encoding="utf-8").read().strip()


def main():
	version = read(STAMP, "product version")
	build = read(RTSTAMP, "runtime build number")

	if not build.isdigit():
		die('rtbuild.txt = "%s": not a number -- it names GPC.RT.nnn.BIN' % build)
	build = int(build)
	if not 0 <= build <= 999:
		die("rtbuild.txt = %d: bootstrap.asm formats it as %%03d, so it must be 0..999" % build)

	if "--bump" in sys.argv[1:]:
		print("  bumpbuild: --bump ignored -- both stamps are edited by hand now (see header)")

	#
	#		Create the directory rather than tracking it: git cannot track an empty one, and a
	#		fresh clone would then fail on its very first build -- which is exactly how
	#		common-source/scripts/ broke every clone of this repo once already.
	#
	os.makedirs(GENDIR, exist_ok=True)

	#
	#		Uppercase 'V' deliberately: the X16 screen boots in PETSCII upper/graphics, where
	#		lowercase bytes come out as graphics glyphs rather than letters.
	#
	#		BuildNumber is emitted outside the code section: it is a symbol, not bytes.
	#
	with open(OUT, "w", encoding="utf-8", newline="\n") as h:
		h.write(";\n;\tThis file is automatically generated by scripts/bumpbuild.py\n;\n")
		h.write("BuildNumber = %d\n" % build)
		h.write("\t\t.section code\n")
		h.write("VersionText:\n")
		h.write("\t\t.text\t'V%s',13,0\n" % version)
		#
		#		The runtime image the compiler streams into every embedded object. Numbered
		#		from the SAME stamp as the shared runtime, and for the same reason: under a
		#		fixed name a stale image would still be found, and would produce a program
		#		that loads and then misbehaves. Numbered, a stale one is simply not there and
		#		WriteObjectCode says NO RUNTIME IMAGE rather than writing a broken object.
		#
		h.write("RTImageFileText:\n")
		h.write("\t\t.text\t'GPC.IMG.%03d.BIN',0\n" % build)
		h.write("\t\t.send code\n")

	print("  bumpbuild: GPC V%s, runtime build %03d (GPC.RT.%03d.BIN, GPC.IMG.%03d.BIN)"
		  % (version, build, build, build))


main()
