# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		bumpbuild.py
#		Purpose :	Bump the engine's build number, generate source/generated/version.asm
#		Date :		30th July 2026
#
# *******************************************************************************************
# *******************************************************************************************
#
#		The build number belongs to the ENGINE (GPC.BLITZ.BIN), because the engine is the part
#		that actually compiles and therefore the part you need to identify. It used to live in
#		the front end -- VERSION$ in GPC.BASL -- and bumped only when the FRONT END was
#		rebuilt, so it never moved when the compiler itself changed. That made it useless for
#		the one question a build number exists to answer: "am I running my fix?"
#
#		buildnum.txt holds the whole version, MAJOR.MINOR.BUILD. The last component bumps on
#		every engine build; change MAJOR.MINOR by hand when cutting a release. release.sh
#		reads the same file to name the release zip, so there is still exactly one source of
#		truth -- it has just moved from the front end to the engine.
#
#		TWO MODES, because the number must advance exactly once per build:
#
#			bumpbuild.py --bump	 increment buildnum.txt, then write version.asm
#			bumpbuild.py		 write version.asm from buildnum.txt (no increment)
#
#		source/application is built more than once per build -- source/Makefile enters it from
#		both `libraries` and `release`, and build.sh then runs `make release` again on top -- so
#		bumping in the application's own prelim counted one build as three. The bump therefore
#		happens once, at the top of source/Makefile's `libraries`; every other entry only
#		regenerates version.asm, which is idempotent. A release ships the number it was built
#		with rather than inventing a new one.
#
# *******************************************************************************************

import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)								# source/application
STAMP = os.path.join(APP, "buildnum.txt")
GENDIR = os.path.join(APP, "source", "generated")
OUT = os.path.join(GENDIR, "version.asm")


def die(msg):
	sys.exit("  bumpbuild: FAIL -- " + msg)


def main():
	if not os.path.isfile(STAMP):
		die("%s is missing -- it holds the engine version and is tracked in git" % STAMP)

	version = open(STAMP, encoding="utf-8").read().strip()
	parts = version.split(".")
	if not parts[-1].isdigit():
		die('buildnum.txt = "%s": last component is not a number -- cannot use it' % version)

	bump = "--bump" in sys.argv[1:]
	if bump:
		parts[-1] = str(int(parts[-1]) + 1)
		version = ".".join(parts)
		with open(STAMP, "w", encoding="utf-8", newline="\n") as h:
			h.write(version + "\n")

	#
	#		Create the directory rather than tracking it: git cannot track an empty one, and a
	#		fresh clone would then fail on its very first build -- which is exactly how
	#		common-source/scripts/ broke every clone of this repo once already.
	#
	os.makedirs(GENDIR, exist_ok=True)

	#
	#		Uppercase 'V' deliberately: the X16 screen boots in PETSCII upper/graphics, where
	#		lowercase bytes come out as graphics glyphs rather than letters.
	#
	#
	#		BuildNumber is the last dotted component as a NUMBER, not text. bootstrap.asm
	#		formats it into the resident runtime's file name (GPC.RT.<build>.BIN), so the
	#		name a compiled program looks for and the name rtname.py builds the runtime as
	#		both come from this one stamp. It is emitted outside the code section: it is a
	#		symbol, not bytes.
	#
	build = int(parts[-1])

	with open(OUT, "w", encoding="utf-8", newline="\n") as h:
		h.write(";\n;\tThis file is automatically generated by scripts/bumpbuild.py\n;\n")
		h.write("BuildNumber = %d\n" % build)
		h.write("\t\t.section code\n")
		h.write("VersionText:\n")
		h.write("\t\t.text\t'V%s',13,0\n" % version)
		h.write("\t\t.send code\n")

	print("  bumpbuild: engine build %s%s" % (version, " (bumped)" if bump else ""))


main()
